# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('board_id', models.CharField(help_text=b'this is the rapidView id in the jira url', max_length=20)),
                ('custom_field_name_for_issue_order', models.CharField(default=b'customfield_10006', help_text=b'the name of the field used to hold the issue sorting value ', max_length=20)),
                ('sync_actual_times', models.BooleanField(default=False)),
                ('sync_issue_ordering_to_jira', models.BooleanField(default=False)),
                ('sync_issue_ordering_from_jira', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira', to='timepiece.Business')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('jira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira_interface.Jira')),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_username', models.CharField(max_length=255)),
                ('jira_password', models.CharField(max_length=255)),
                ('jira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira_interface.Jira')),
                ('timepiece_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
