# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedVisualSpecDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('problem_type', models.CharField(choices=[(b'missing_rate', b'Missing rate'), (b'missing_budget', b'Missing budget')], max_length=100)),
                ('money_sensitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(b'open', b'Open'), (b'closed', b'Closed'), (b'cant_fix', b"Can't fix")], default=b'open', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to='timepiece.Business')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to='timepiece.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('decision_made_at', models.DateTimeField()),
                ('decision', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('repercussions', models.TextField(blank=True, null=True)),
                ('decision_made_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionJournalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('decision_journal_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_decision_journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='imptime.DecisionJournal')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(null=True)),
                ('issues', models.ManyToManyField(related_name='features', to='timepiece.Issue')),
                ('parent', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='imptime.Feature')),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('feature_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='imptime.Feature')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('issue_headers', models.TextField(blank=True, null=True)),
                ('nudge_headers', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MienHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('headers', models.TextField(blank=True, null=True)),
                ('mien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='imptime.Mien')),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('due_date_reason', models.CharField(max_length=255, null=True)),
                ('estimated_start_at', models.DateTimeField(null=True)),
                ('estimated_end_at', models.DateTimeField(null=True)),
                ('estimated_hours', models.FloatField(null=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='timepiece.Issue')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='timepiece.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFeatureOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_feature_orders', to='imptime.Feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWikiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('header', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseNoteSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(auto_now=True)),
                ('release_note', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seen_by', to='imptime.ReleaseNote')),
                ('seen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_notes_seen_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=True)),
                ('editors', models.ManyToManyField(related_name='editable_schedules', to=settings.AUTH_USER_MODEL)),
                ('owner', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schedules', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='viewable_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('start_at', models.DateTimeField(db_index=True, null=True)),
                ('end_at', models.DateTimeField(db_index=True, null=True)),
                ('duration_hours', models.FloatField(null=True)),
                ('issue', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Issue')),
                ('project', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Business')),
                ('schedule', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='imptime.Schedule')),
                ('sprint', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SprintSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('cost_summary', models.TextField(null=True)),
                ('project_statement', models.TextField(null=True)),
                ('time_summary', models.TextField(null=True)),
                ('affected_entities', models.TextField(null=True)),
                ('estimate_time_summary', models.TextField(null=True)),
                ('sprint', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SprintTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('clones', models.ManyToManyField(related_name='parent_sprint_templates', to='timepiece.Project')),
                ('sprint', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNudgeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('nudge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_orders', to='imptime.Nudge', unique=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[(b'circle', b'Circle'), (b'square', b'Square'), (b'arrow', b'Arrow')], default=b'circle', max_length=50)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('x_offset_to_target', models.FloatField()),
                ('y_offset_to_target', models.FloatField()),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='imptime.AnnotatedVisualSpecDocument')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('original_doc', models.FileField(max_length=255, upload_to=lib.fields.UploadTo(b'visual_spec_documents'))),
                ('hires', lib.fields.HiResImageField(blank=True, null=True, upload_to=lib.fields.UploadTo(b'visual_spec_documents'))),
                ('thumbnail', lib.fields.ThumbnailImageField(null=True, upload_to=lib.fields.UploadTo(b'visual_spec_documents'))),
                ('hires_width', models.IntegerField()),
                ('hires_height', models.IntegerField()),
                ('md5sum', models.CharField(max_length=255)),
                ('is_image', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255, null=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_features', to='imptime.AnnotatedVisualSpecDocument')),
                ('deprecated_visual_spec_document', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.VisualSpecDocument')),
                ('feature', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='VisualSpecIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_issues', to='imptime.AnnotatedVisualSpecDocument')),
                ('deprecated_visual_spec_document', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='imptime.VisualSpecDocument')),
                ('issue', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='timepiece.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='VisualSpecProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_projects', to='timepiece.Business')),
                ('visual_spec_document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_projects', to='imptime.VisualSpecDocument')),
            ],
        ),
        migrations.CreateModel(
            name='VisualSpecWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_wikis', to='imptime.AnnotatedVisualSpecDocument')),
                ('deprecated_visual_spec_document', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_wikis', to='imptime.VisualSpecDocument')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('money_sensitive', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('enriched_content', models.TextField(null=True)),
                ('store_encrypted', models.BooleanField(default=False)),
                ('parent', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='imptime.WikiPage')),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wikis', to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiPageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('wiki_page_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_wiki_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='imptime.WikiPage')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='visualspecwiki',
            name='wiki',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_wikis', to='imptime.WikiPage'),
        ),
        migrations.AddField(
            model_name='projectwikiorder',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_wiki_orders', to='imptime.WikiPage'),
        ),
        migrations.AddField(
            model_name='annotatedvisualspecdocument',
            name='visual_spec_document',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotated_visual_spec_document', to='imptime.VisualSpecDocument'),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecwiki',
            unique_together=set([('wiki', 'annotated_visual_spec_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecproject',
            unique_together=set([('project', 'visual_spec_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecissue',
            unique_together=set([('issue', 'annotated_visual_spec_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecfeature',
            unique_together=set([('feature', 'annotated_visual_spec_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectwikiorder',
            unique_together=set([('project', 'wiki')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectfeatureorder',
            unique_together=set([('project', 'feature')]),
        ),
        migrations.AlterUniqueTogether(
            name='mienheader',
            unique_together=set([('mien', 'name')]),
        ),
    ]
