# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0057_auto_20170906_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('shape', models.CharField(choices=[(b'circle', b'Circle')], default=b'circle', max_length=50)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('issue', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_issues', to='timepiece.Issue')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('document', models.FileField(max_length=255, upload_to=lib.fields.UploadTo(b'visual_spec_documents'))),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('issue', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_documents', to='timepiece.Issue')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='visualissue',
            name='visual_spec_document',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_documents', to='imptime.VisualSpecDocument'),
        ),
    ]
