# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 20:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualissue',
            name='visual_spec_document',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_issues', to='imptime.VisualSpecDocument'),
        ),
    ]
