# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0002_auto_20171021_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisualIssue',
            new_name='VisualSpecIssue',
        ),
    ]
