# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0003_auto_20171022_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecissue',
            name='issue',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='timepiece.Issue'),
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='shape',
            field=models.CharField(choices=[(b'circle', b'Circle'), (b'pointer', b'Pointer')], default=b'circle', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='visual_spec_document',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='imptime.VisualSpecDocument'),
        ),
    ]
