# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0004_auto_20171025_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecissue',
            name='x_pos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='y_pos',
            field=models.FloatField(),
        ),
    ]
