# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 15:00
from __future__ import unicode_literals

from django.db import migrations
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0005_auto_20171026_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualspecdocument',
            name='hires',
            field=lib.fields.HiResImageField(blank=True, null=True, upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
        ),
    ]
