# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 15:29
from __future__ import unicode_literals

from django.db import migrations
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0006_visualspecdocument_hires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualspecdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='visualspecdocument',
            name='lores',
            field=lib.fields.LoResImageField(default='dud', upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualspecdocument',
            name='thumbnail',
            field=lib.fields.ThumbnailImageField(default='dud', upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
            preserve_default=False,
        ),
    ]
