# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0007_auto_20171028_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualspecdocument',
            name='hires_height',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualspecdocument',
            name='hires_width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
