# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0008_auto_20171028_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualspecissue',
            name='order',
        ),
        migrations.AddField(
            model_name='visualspecdocument',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
