# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0062_project_project_type'),
        ('imptime', '0009_auto_20171028_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('clones', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cloned_from_sprint_template', to='timepiece.Project')),
                ('sprint', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
