# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 21:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0010_sprinttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttemplate',
            name='clones',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cloned_from_sprint_template', to='timepiece.Project'),
        ),
    ]
