# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0063_auto_20171031_2106'),
        ('imptime', '0011_auto_20171031_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprinttemplate',
            name='clones',
        ),
        migrations.AddField(
            model_name='sprinttemplate',
            name='clones',
            field=models.ManyToManyField(null=True, related_name='parent_sprint_templates', to='timepiece.Project'),
        ),
    ]
