# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0012_auto_20171031_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttemplate',
            name='clones',
            field=models.ManyToManyField(related_name='parent_sprint_templates', to='timepiece.Project'),
        ),
    ]
