# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0014_releasenote_releasenoteseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenote',
            name='created_by',
        ),
    ]
