# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 18:19
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    ReleaseNote = apps.get_model('imptime', 'ReleaseNote')
    ReleaseNote(header="Improved multiple issue selection",
                content="Use shift to select multiple issues. If one of those issues is a collapsed Feature issue, all its children are selected too").save()
    ReleaseNote(header="Added bulk issue creation",
                content="On the sprint and issue toolbars, there is a button to create bulk issues. It uses the same format as emails sent to imptime").save()

class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0015_remove_releasenote_created_by'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
