# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0088_auto_20171116_2013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imptime', '0035_release_notes_username_16Nov2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('nudginess_percent', models.FloatField()),
                ('issue_id', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nudges', to='timepiece.Issue')),
                ('sprint', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nudges', to='timepiece.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
