# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0036_nudge'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='reason',
            field=models.CharField(blank=True, choices=[(b'assigned_issues', b'Assigned issues'), (b'pending_reviews', b'Pending reviews'), (b'deadlines', b'Deadlines'), (b'invalid_rates', b'Invalid rates'), (b'invalid_budgets', b'Invalid budgets'), (b'invalid_timesheets', b'Invalid timesheets'), (b'appointments', b'Appointments'), (b'inactive_projects', b'Inactive projects')], max_length=255, null=True),
        ),
    ]
