# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 20:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0088_auto_20171116_2013'),
        ('imptime', '0037_auto_20171116_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nudge',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='nudge',
            name='issue',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nudges', to='timepiece.Issue'),
        ),
    ]
