# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0037_release_notes_issue_sidebar_toggle_17Nov2017'),
        ('imptime', '0038_auto_20171116_2051'),
    ]

    operations = [
    ]
