# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0040_release_notes_breadcrumb_links_are_17Nov2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nudge',
            name='nudginess_percent',
        ),
        migrations.AddField(
            model_name='nudge',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nudge',
            name='due_date_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
