# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 20:58
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    VisualSpecDocument = apps.get_model('imptime', 'VisualSpecDocument')
    VisualSpecIssue = apps.get_model('imptime', 'VisualSpecIssue')
    VisualSpecIssue.objects.all().delete()
    VisualSpecDocument.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0042_release_notes_nudges_18Nov2017'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
