# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0088_auto_20171116_2013'),
        ('imptime', '0043_delete_existing_visual_spec_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualSpecIssueAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[(b'circle', b'Circle'), (b'pointer', b'Pointer')], default=b'circle', max_length=50)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_projects', to='timepiece.Business')),
            ],
        ),
        migrations.AlterModelOptions(
            name='visualspecissue',
            options={},
        ),
        migrations.RemoveField(
            model_name='visualspecdocument',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='visualspecdocument',
            name='order',
        ),
        migrations.AddField(
            model_name='visualspecissue',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='visualspecissue',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='visualspecissue',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='visualspecissue',
            name='y_pos',
        ),
        migrations.AlterUniqueTogether(
            name='visualspecissue',
            unique_together=set([('issue', 'visual_spec_document')]),
        ),
        migrations.AddField(
            model_name='visualspecproject',
            name='visual_spec_document',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_projects', to='imptime.VisualSpecDocument'),
        ),
        migrations.AddField(
            model_name='visualspecissueannotation',
            name='visual_spec_issue',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issue_annotations', to='imptime.VisualSpecIssue'),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecproject',
            unique_together=set([('project', 'visual_spec_document')]),
        ),
    ]
