# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0044_auto_20171118_2059'),
        ('imptime', '0044_release_notes_testables_in_order_20Nov2017'),
    ]

    operations = [
    ]
