# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0049_release_notes_issue_quality_21Nov2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualspecdocument',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visualspecdocument',
            name='original_doc',
            field=models.FileField(default='123', upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualspecissueannotation',
            name='shape',
            field=models.CharField(choices=[(b'circle', b'Circle'), (b'square', b'Square'), (b'pointer', b'Pointer')], default=b'circle', max_length=50),
        ),
    ]
