# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0050_auto_20171121_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualspecissueannotation',
            name='x_offset_to_target',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualspecissueannotation',
            name='y_offset_to_target',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualspecissueannotation',
            name='shape',
            field=models.CharField(choices=[(b'circle', b'Circle'), (b'square', b'Square'), (b'arrow', b'Arrow')], default=b'circle', max_length=50),
        ),
    ]
