# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0051_auto_20171122_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecissueannotation',
            name='visual_spec_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_issue_annotations', to='imptime.VisualSpecIssue'),
        ),
    ]
