# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0053_release_notes_visual_spec_document_25Nov2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecdocument',
            name='original_doc',
            field=models.FileField(max_length=255, upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
        ),
    ]
