# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0076_release_notes_new_issue_sprint_sel_05Dec2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nudge',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='timepiece.Issue'),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='timepiece.Project'),
        ),
    ]
