# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-07 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0077_release_notes_selection_colour_dar_05Dec2017'),
        ('imptime', '0081_release_notes_tag_columns_21Dec2017'),
    ]

    operations = [
    ]
