# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0083_release_notes_Issue_feature_editin_09Jan2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualspecdocument',
            name='md5sum',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
