# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0096_tag_name_to_lower'),
        ('imptime', '0087_release_notes_bug_fix_for_sprint_c_29Jan2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wikis', to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('money_sensitive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectwiki',
            name='wiki_page',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_wikis', to='imptime.WikiPage'),
        ),
    ]
