# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0088_auto_20180129_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='money_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
