# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 15:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0096_tag_name_to_lower'),
        ('imptime', '0089_auto_20180129_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwiki',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectwiki',
            name='wiki_page',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='project_id',
            field=lib.fields.ProtectedForeignKey(default=26, on_delete=django.db.models.deletion.PROTECT, related_name='wikis', to='timepiece.Business'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectWiki',
        ),
    ]
