# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0090_auto_20180201_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipage',
            old_name='project_id',
            new_name='project',
        ),
    ]
