# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0088_add_default_sprint_deadline_type_retroactively_02Feb2018'),
        ('imptime', '0092_release_notes_wiki_02Feb2018'),
    ]

    operations = [
    ]
