# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-09 11:42
from __future__ import unicode_literals

from django.db import migrations
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0093_merge_20180207_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecdocument',
            name='lores',
            field=lib.fields.LoResImageField(null=True, upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
        ),
        migrations.AlterField(
            model_name='visualspecdocument',
            name='thumbnail',
            field=lib.fields.ThumbnailImageField(null=True, upload_to=lib.fields.UploadTo(b'visual_spec_documents')),
        ),
    ]
