# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0095_release_notes_autoclock_12Feb2018'),
        ('imptime', '0094_auto_20180209_1142'),
    ]

    operations = [
    ]
