# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0134_release_notes_types_of_comments_27Mar2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='enriched_content',
            field=models.TextField(null=True),
        ),
    ]
