# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0158_mien'),
    ]

    operations = [
        migrations.AddField(
            model_name='mien',
            name='issue_headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
