# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0159_mien_issue_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mien',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
