# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0163_release_notes_bug_fix_for_attachme_15May2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualspecdocument',
            name='lores',
        ),
    ]
