# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-21 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0114_auto_20180504_1403'),
        ('imptime', '0167_release_notes_non-image_attachment_18May2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('problem_type', models.CharField(choices=[(b'missing_rate', b'Missing rate')], max_length=100)),
                ('money_sensitive', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to='timepiece.Business')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to='timepiece.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
