# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-20 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0114_auto_20180504_1403'),
        ('imptime', '0167_release_notes_non-image_attachment_18May2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('editors', models.ManyToManyField(related_name='editable_schedules', to=settings.AUTH_USER_MODEL)),
                ('owner', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schedules', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='viewable_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('duration_hours', models.FloatField(null=True)),
                ('issue', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Issue')),
                ('project', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Business')),
                ('schedule', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='imptime.Schedule')),
                ('sprint', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
