# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-20 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imptime', '0168_schedule_scheduleditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledItem',
            new_name='ScheduleItem',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('name', 'owner')]),
        ),
    ]
