# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0170_merge_20180521_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproblem',
            name='status',
            field=models.CharField(choices=[(b'open', b'Open'), (b'closed', b'Closed'), (b'cant_fix', b"Can't fix")], default=b'open', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='end_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='start_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
