# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0171_auto_20180521_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mien',
            name='nudge_headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
