# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0172_mien_nudge_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MienHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('headers', models.TextField(blank=True, null=True)),
                ('mien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='imptime.Mien')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
