# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 22:04
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Mien = apps.get_model('imptime', 'Mien')
    MienHeader = apps.get_model('imptime', 'MienHeader')

    miens = Mien.objects.all()
    for mien in miens:
        MienHeader.objects.create(mien=mien, name="issue", headers=mien.issue_headers)
        MienHeader.objects.create(mien=mien, name="nudge", headers=mien.nudge_headers)

class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0173_mienheader'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
