# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0174_merge_mien_headers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mienheader',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='mienheader',
            unique_together=set([('mien', 'name')]),
        ),
    ]
