# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0175_auto_20180523_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproblem',
            name='problem_type',
            field=models.CharField(choices=[(b'missing_rate', b'Missing rate'), (b'missing_budget', b'Missing budget')], max_length=100),
        ),
        migrations.AlterField(
            model_name='companyproblem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
