# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0180_release_notes_Enabled_internationa_31May2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
