# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0187_release_notes_bug_fix_for_creating_05Jun2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNudgeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('nudge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_order', to='imptime.Nudge', unique=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
