# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0199_release_notes_Testable_during_bulk_23Jul2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='estimated_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nudge',
            name='estimated_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usernudgeorder',
            name='nudge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_orders', to='imptime.Nudge', unique=True),
        ),
    ]
