# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0200_auto_20180723_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='estimated_hours',
            field=models.FloatField(null=True),
        ),
    ]
