# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-02 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0128_update issue history original_issue_id'),
        ('imptime', '0219_release_notes_blocked_issues_are_o_02Aug2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('sprint', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
