# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0220_sprintsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
