# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0221_sprintsnapshot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='snapshot',
            field=models.TextField(null=True),
        ),
    ]
