# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0222_sprintsnapshot_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprintsnapshot',
            old_name='snapshot',
            new_name='cost_summary',
        ),
    ]
