# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0225_release_notes_emacs_timesheet_impo_06Aug2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='project_statement',
            field=models.TextField(null=True),
        ),
    ]
