# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0226_sprintsnapshot_project_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='time_summary',
            field=models.TextField(null=True),
        ),
    ]
