# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0227_sprintsnapshot_time_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='affected_entities',
            field=models.TextField(null=True),
        ),
    ]
