# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0228_sprintsnapshot_affected_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsnapshot',
            name='estimate_time_summary',
            field=models.TextField(null=True),
        ),
    ]
