# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0249_auto_20180919_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
