# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0253_release_notes_features_link_to_iss_30Sep2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualSpecFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('feature', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.Feature')),
                ('visual_spec_document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.VisualSpecDocument')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='visualspecfeature',
            unique_together=set([('feature', 'visual_spec_document')]),
        ),
    ]
