# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0256_release_notes_feature_filter_07Oct2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualSpecFeatureAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[(b'circle', b'Circle'), (b'square', b'Square'), (b'arrow', b'Arrow')], default=b'circle', max_length=50)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('x_offset_to_target', models.FloatField()),
                ('y_offset_to_target', models.FloatField()),
                ('visual_spec_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_feature_annotations', to='imptime.VisualSpecFeature')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
