# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0257_visualspecfeatureannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedVisualSpecDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('visual_spec_document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotated_visual_spec_document', to='imptime.VisualSpecDocument')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualSpecAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[(b'circle', b'Circle'), (b'square', b'Square'), (b'arrow', b'Arrow')], default=b'circle', max_length=50)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('x_offset_to_target', models.FloatField()),
                ('y_offset_to_target', models.FloatField()),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='imptime.AnnotatedVisualSpecDocument')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='visualspecfeatureannotation',
            name='visual_spec_feature',
        ),
        migrations.RemoveField(
            model_name='visualspecissueannotation',
            name='visual_spec_issue',
        ),
        migrations.DeleteModel(
            name='VisualSpecFeatureAnnotation',
        ),
        migrations.DeleteModel(
            name='VisualSpecIssueAnnotation',
        ),
        migrations.AddField(
            model_name='visualspecfeature',
            name='annotated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.AnnotatedVisualSpecDocument'),
        ),
        migrations.AddField(
            model_name='visualspecissue',
            name='annotated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='imptime.AnnotatedVisualSpecDocument'),
        ),
    ]
