# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 18:47
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    AnnotatedVisualSpecDocument = apps.get_model('imptime', 'AnnotatedVisualSpecDocument')
    VisualSpecIssue = apps.get_model('imptime', 'VisualSpecIssue')
    VisualSpecFeature = apps.get_model('imptime', 'VisualSpecFeature')

    for vsi in VisualSpecIssue.objects.all():
        annotated_doc = AnnotatedVisualSpecDocument.objects.create(visual_spec_document=vsi.visual_spec_document)
        vsi.annotated_visual_spec_document = annotated_doc
        vsi.save()

    for vsf in VisualSpecFeature.objects.all():
        annotated_doc = AnnotatedVisualSpecDocument.objects.create(visual_spec_document=vsf.visual_spec_document)
        vsf.annotated_visual_spec_document = annotated_doc
        vsf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0258_auto_20181009_2046'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
