# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 18:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0134_auto_20180919_1940'),
        ('imptime', '0259_create_annotated_vsd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualspecfeature',
            old_name='visual_spec_document',
            new_name='deprecated_visual_spec_document',
        ),
        migrations.RenameField(
            model_name='visualspecissue',
            old_name='visual_spec_document',
            new_name='deprecated_visual_spec_document',
        ),
        migrations.AlterField(
            model_name='visualspecfeature',
            name='annotated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.AnnotatedVisualSpecDocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='annotated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='imptime.AnnotatedVisualSpecDocument'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visualspecfeature',
            unique_together=set([('feature', 'annotated_visual_spec_document')]),
        ),
        migrations.AlterUniqueTogether(
            name='visualspecissue',
            unique_together=set([('issue', 'annotated_visual_spec_document')]),
        ),
    ]
