# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-10 11:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0260_auto_20181009_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualspecfeature',
            name='deprecated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_features', to='imptime.VisualSpecDocument'),
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='deprecated_visual_spec_document',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_issues', to='imptime.VisualSpecDocument'),
        ),
    ]
