# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0135_auto_20181016_2140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imptime', '0265_release_notes_quick_create_assigne_15Oct2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('decision_made_at', models.DateTimeField(auto_now=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('repercussions', models.TextField(blank=True, null=True)),
                ('decision_made_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionJournalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('decision_journal_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_decision_journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='imptime.DecisionJournal')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='visualspecfeature',
            name='annotated_visual_spec_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_features', to='imptime.AnnotatedVisualSpecDocument'),
        ),
        migrations.AlterField(
            model_name='visualspecissue',
            name='annotated_visual_spec_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_issues', to='imptime.AnnotatedVisualSpecDocument'),
        ),
    ]
