# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0269_release_notes_permission_websocket_18Oct2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='store_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decisionjournal',
            name='decision_made_at',
            field=models.DateTimeField(),
        ),
    ]
