# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imptime', '0271_release_notes_encrypted_wikis_adde_20Oct2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualSpecWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('annotated_visual_spec_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_spec_wikis', to='imptime.AnnotatedVisualSpecDocument')),
                ('deprecated_visual_spec_document', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_wikis', to='imptime.VisualSpecDocument')),
                ('wiki', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_spec_wikis', to='imptime.WikiPage')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('wiki_page_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_wiki_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='imptime.WikiPage')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='visualspecwiki',
            unique_together=set([('wiki', 'annotated_visual_spec_document')]),
        ),
    ]
