# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 15:33
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    CompanyPermissions = apps.get_model('timepiece', 'CompanyPermissions')
    Company = apps.get_model('timepiece', 'Company')
    User = apps.get_model('auth', 'User')

    company = Company.objects.get(name='Implicit Design')

    for username in [ 'gtp', 'olivia' ]:
        user = User.objects.get(username='gtp')
        cp = CompanyPermissions.objects.get_or_create(company=company, user=user)[0]
        cp.is_active_member_of_company = True
        cp.can_invite_users = True
        cp.can_set_user_permissions = True
        cp.can_edit_company_info = True
        cp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0275_release_notes_companies_added_27Oct2018'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
