# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0287_release_notes_attachment_annotatio_24Jan2019'),
        ('imptime', '0288_release_notes_sprint_rename_bug_23Jan2019'),
    ]

    operations = [
    ]
