# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-12 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0303_release_notes_fixes_add_user_to_pr_12Mar2019'),
        ('imptime', '0307_release_notes_fix_due_issues_popup_11Mar2019'),
    ]

    operations = [
    ]
