# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-26 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0311_release_notes_search_bug_fix_15Mar2019'),
        ('imptime', '0304_release_notes_Fixes_error_on_Sprin_26Mar2019'),
    ]

    operations = [
    ]
