# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 17:01
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    STATUSES = ( ('step1', 'step1 - gather requirements - needed'),
                 ('step1', 'step1 - gather requirements - in progress'),
                 ('step1', 'step1 - gather requirements - done'),
                 ('step1', 'step1 - gather requirements - approved'),
                 ('step2', 'step2 - wireframes - needed'),
                 ('step2', 'step2 - wireframes - in progress'),
                 ('step2', 'step2 - wireframes - done'),
                 ('step2', 'step2 - wireframes - approved'),
                 ('step3', 'step3 - pretty pictures - needed'),
                 ('step3', 'step3 - pretty pictures - in progress'),
                 ('step3', 'step3 - pretty pictures - done'),
                 ('step3', 'step3 - pretty pictures - approved'),
                 ('step4', 'step4 - create issues and testables - needed'),
                 ('step4', 'step4 - create issues and testables - in progress'),
                 ('step4', 'step4 - create issues and testables - done'),
                 ('step4', 'step4 - create issues and testables - approved'),
                 ('step5', 'step5 - estimate - needed'),
                 ('step5', 'step5 - estimate - in progress'),
                 ('step5', 'step5 - estimate - done'),
                 ('step5', 'step5 - estimate - approved'),
                 ('step6', 'step6 - client go ahead - needed'),
                 ('step6', 'step6 - client go ahead - in progress'),
                 ('step6', 'step6 - client go ahead - done'),
                 ('step6', 'step6 - client go ahead - approved'),
                 ('step7', 'step7 - development - needed'),
                 ('step7', 'step7 - development - in progress'),
                 ('step7', 'step7 - development - done'),
                 ('step7', 'step7 - development - approved'),
                 ('step8', 'step8 - testing - needed'),
                 ('step8', 'step8 - testing - in progress'),
                 ('step8', 'step8 - testing - done'),
                 ('step8', 'step8 - testing - approved'),
                 ('step9', 'step9 - handover - needed'),
                 ('step9', 'step9 - handover - in progress'),
                 ('step9', 'step9 - handover - done'),
                 ('step9', 'step9 - handover - approved'),
                 ('step10', 'step10 - release - needed'),
                 ('step10', 'step10 - release - in progress'),
                 ('step10', 'step10 - release - done'),
                 ('step10', 'step10 - release - approved'),
                 ('waiting to invoice', 'waiting to invoice'),
                 ('invoiced', 'invoiced'),
                 ('waiting to close', 'waiting to close'),
                 ('on hold', 'on hold'),
                 ('closed', 'closed') )

    Project = apps.get_model('timepiece', 'Business') #sic
    SprintStatus = apps.get_model('timepiece', 'ProjectStatus') #sic

    for project in Project.objects.all():
        for code, name in STATUSES:
            SprintStatus.objects.get_or_create(name=name, business=project, is_closed=(code=='closed')) #sic
    

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0147_set_closed_sprint_Status'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
