# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0314_release_notes_new_sprint_statuses_02Apr2019'),
        ('imptime', '0312_merge_20190327_0013'),
    ]

    operations = [
    ]
