# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0147_set_closed_sprint_Status'),
        ('imptime', '0321_release_notes_multi-select_sprints_09Apr2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWikiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
            ],
        ),
        migrations.AddField(
            model_name='wikipage',
            name='parent',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='imptime.WikiPage'),
        ),
        migrations.AddField(
            model_name='projectwikiorder',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_wiki_orders', to='imptime.WikiPage'),
        ),
        migrations.AlterUniqueTogether(
            name='projectwikiorder',
            unique_together=set([('project', 'wiki')]),
        ),
    ]
