# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0318_release_notes_sprint_breadcrumb_fi_04Apr2019'),
        ('imptime', '0322_release_notes_bulk_issue_importer__10Apr2019'),
        ('imptime', '0323_release_notes_company_page_bug_11Apr2019'),
    ]

    operations = [
    ]
