# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-16 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0325_release_notes_uncertainty_bug_fix_16Apr2019'),
        ('imptime', '0325_release_notes_Bug_fix:_adding_a_us_15Apr2019'),
    ]

    operations = [
    ]
