# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-18 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imptime', '0328_release_notes_Maintenance_auto_rel_17Apr2019'),
        ('imptime', '0328_release_notes_fixes_multi-select_o_17Apr2019'),
    ]

    operations = [
    ]
