# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NouiCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('command_function', models.TextField(blank=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NouiCommandParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('var_name', models.CharField(blank=True, max_length=255)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('search_function', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('command', lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='noui.NouiCommand')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('target_device', models.CharField(blank=True, max_length=255, null=True)),
                ('human_readable_source_command', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(b'waiting', b'Waiting'), (b'refused', b'Refused'), (b'failed', b'Failed'), (b'completed', b'Completed')], db_index=True, max_length=20)),
                ('action_type', models.CharField(choices=[(b'redirect', b'Redirect'), (b'javascript', b'Javascript'), (b'run_search_result', b'Run search result')], max_length=20)),
                ('action_args', models.TextField(blank=True, null=True)),
                ('source_command', lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='noui_posted_actions', to='noui.NouiCommand')),
                ('source_user', lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='noui_posted_actions_as_source', to=settings.AUTH_USER_MODEL)),
                ('target_user', lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='noui_posted_actions_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
