# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noui', '0010_auto_20160126_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouicommand',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nouicommand',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nouicommandparameter',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nouicommandparameter',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postedaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postedaction',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
