server {
    listen 80;
    access_log /opt/imptime/logs/imptime-proxy-access.80.log;
    error_log /opt/imptime/logs/imptime-proxy-error.80.log;

    location /.well-known/acme-challenge {
        default_type "text/plain";
        root        /usr/share/nginx/certs_wellknown;
    }

    location / {
        return 301 https://$host$request_uri;
    }      
}
