# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0052_businesspermissions_can_view_testables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_in_regression_test', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='testables', to='timepiece.Issue')),
            ],
        ),
    ]
