# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0001_initial'),
        ('imptime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_in_regression_test', models.BooleanField(default=True)),
                ('name', models.TextField(null=True)),
                ('steps', models.TextField(null=True)),
                ('enriched_steps', models.TextField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('quality_error', models.CharField(max_length=255, null=True)),
                ('features', models.ManyToManyField(related_name='testables', to='imptime.Feature')),
                ('implementing_issues', models.ManyToManyField(related_name='implements_testables', to='timepiece.Issue')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testables', to='timepiece.Issue')),
                ('project', lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='testables', to='timepiece.Business')),
            ],
        ),
        migrations.CreateModel(
            name='TestableLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('refers_to_testable', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_by_testable_lines', to='testable.Testable')),
                ('testable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_lines', to='testable.Testable')),
            ],
        ),
        migrations.CreateModel(
            name='TestableResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'untested', b'Untested'), (b'failed', b'Failed'), (b'passed', b'Passed')], default=b'untested', max_length=10)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to=settings.AUTH_USER_MODEL)),
                ('testable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to='testable.Testable')),
            ],
        ),
        migrations.CreateModel(
            name='TestableSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='timepiece.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testableresult',
            name='testable_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to='testable.TestableSession'),
        ),
    ]
