# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='steps',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
