# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 09:45
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Issue = apps.get_model('timepiece.Issue')
    Testable = apps.get_model('testable.Testable')
    Testable.objects.bulk_create([Testable(issue=x) for x in Issue.objects.all()])

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
