# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0002_testable_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
