# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testable', '0004_testable_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'unknown', b'Unknown'), (b'failed', b'Failed'), (b'passed', b'Passed')], default=b'unknown', max_length=10)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_events', to=settings.AUTH_USER_MODEL)),
                ('testable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_events', to='testable.Testable')),
            ],
        ),
    ]
