# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0005_testevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
