# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0052_businesspermissions_can_view_testables'),
        ('testable', '0006_testevent_is_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestableResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'untested', b'Untested'), (b'failed', b'Failed'), (b'passed', b'Passed')], default=b'untested', max_length=10)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to=settings.AUTH_USER_MODEL)),
                ('testable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to='testable.Testable')),
            ],
        ),
        migrations.CreateModel(
            name='TestableSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='timepiece.Business')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='testevent',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='testevent',
            name='testable',
        ),
        migrations.DeleteModel(
            name='TestEvent',
        ),
        migrations.AddField(
            model_name='testableresult',
            name='testable_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='testable_results', to='testable.TestableSession'),
        ),
    ]
