# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0007_auto_20170630_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testablesession',
            old_name='checked_by',
            new_name='created_by',
        ),
    ]
