# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 18:51
from __future__ import unicode_literals

from django.db import migrations
import re
import logging
logger = logging.getLogger(__name__)

def testable__update_from_issue_description(Testable, issue, description):
    Testable.objects.filter(issue=issue).delete()
    groups = re.split("testable", description, flags=re.IGNORECASE)
    import pdb;pdb.set_trace()
    if len(groups) <= 1:
        return
    step_groups = groups[1:]
    import pdb;pdb.set_trace()
    for step_group in step_groups:
        Testable.objects.create(steps=step_group, issue=issue)

def forwards_func(apps, schema_editor):
    Issue = apps.get_model('timepiece.Issue')
    Testable = apps.get_model('testable.Testable')
    count = Issue.objects.all().count()
    logger.info("Creating testables for %d issues" % count)
    for issue in Issue.objects.all():
        count -= 1
        if count % 100 == 0:
            logger.info("%d issues left" % count)
        testable__update_from_issue_description(Testable, issue, issue.description)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0009_auto_20170630_1013'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
