# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0010_create_initial_testables_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='quality_error',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
