# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0011_testable_quality_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='enriched_steps',
            field=models.TextField(null=True),
        ),
    ]
