# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0134_auto_20180919_1940'),
        ('imptime', '0250_feature_number'),
        ('testable', '0012_testable_enriched_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestableStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='testable',
            name='features',
            field=models.ManyToManyField(related_name='testables', to='imptime.Feature'),
        ),
        migrations.AddField(
            model_name='testable',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testable',
            name='project',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testables', to='timepiece.Business'),
        ),
        migrations.AlterField(
            model_name='testable',
            name='issue',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testables', to='timepiece.Issue'),
        ),
        migrations.AddField(
            model_name='testablestep',
            name='refers_to_testable',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referred_by_testable_steps', to='testable.Testable'),
        ),
        migrations.AddField(
            model_name='testablestep',
            name='testable',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testable_steps', to='testable.Testable'),
        ),
    ]
