# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 15:36
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Testable = apps.get_model('testable.Testable')
    for testable in Testable.objects.all():
        testable.project_id = testable.issue.project.business_id
        testable.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0013_auto_20180925_1736'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
