# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-25 15:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0014_update_testable_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testable',
            name='project',
            field=lib.fields.ProtectedForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='testables', to='timepiece.Business'),
        ),
    ]
