# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-30 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0134_auto_20180919_1940'),
        ('testable', '0015_auto_20180925_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='testable',
            name='implementing_issues',
            field=models.ManyToManyField(related_name='implements_testables', to='timepiece.Issue'),
        ),
    ]
