# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0016_testable_implementing_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testable',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testables', to='timepiece.Issue'),
        ),
    ]
