# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0017_auto_20180930_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestableLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('refers_to_testable', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referred_by_testable_lines', to='testable.Testable')),
                ('testable', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testable_lines', to='testable.Testable')),
            ],
        ),
        migrations.RemoveField(
            model_name='testablestep',
            name='refers_to_testable',
        ),
        migrations.RemoveField(
            model_name='testablestep',
            name='testable',
        ),
        migrations.DeleteModel(
            name='TestableStep',
        ),
    ]
