# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0018_auto_20190120_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testableline',
            name='instruction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testableline',
            name='refers_to_testable',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_by_testable_lines', to='testable.Testable'),
        ),
    ]
