# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0019_auto_20190123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testable',
            name='steps',
            field=models.TextField(null=True),
        ),
    ]
