# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0020_auto_20190124_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testableline',
            name='testable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testable_lines', to='testable.Testable'),
        ),
    ]
