# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 19:55
from __future__ import unicode_literals
import re
from django.db import migrations

CONVERTED_TOKEN="__CONVERTED__"
def convert_to_testable_lines(testable, apps):
    if not testable.steps or testable.steps.startswith(CONVERTED_TOKEN):
        return
    TestableLine = apps.get_model('testable.TestableLine')
    lines = TestableLine.objects.filter(testable_id=testable.id)
    lines.delete()
    order = 1
    for line in testable.steps.split("\n"):
        if line.startswith("- "):
            line = line[2:]
        if re.match(r'^[^ ]*\. ', line):
            line = line[3:]
        TestableLine.objects.create(instruction=line,
                                    testable_id=testable.id,
                                    order=order)
        order+=1
    testable.steps = CONVERTED_TOKEN + testable.steps
    testable.save()

def forwards_func(apps, schema_editor):
    Testable = apps.get_model('testable.Testable')
    for testable in Testable.objects.all().filter():
        convert_to_testable_lines(testable, apps)

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('testable', '0021_auto_20190124_2034'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
