FROM ubuntu:16.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  git \
  libjpeg-dev \
  libxml2-dev \
  libxslt1-dev \
  nodejs-legacy \
  npm \
  python-dev \
  postgresql-server-dev-9.5 \
  redis-server \
  virtualenv

COPY start-django.sh start-django.sh

ENTRYPOINT ["./start-django.sh"]
