FROM imptime/base:latest

# Build sassc
WORKDIR /tmp/
RUN git clone https://github.com/sass/sassc.git --branch 3.4 --depth 1
RUN git clone https://github.com/sass/libsass.git --branch 3.4 --depth 1
WORKDIR /tmp/sassc
RUN export SASS_LIBSASS_PATH="/tmp/libsass" && make
RUN export SASS_LIBSASS_PATH="/tmp/libsass" && make install

# Build
# Note: build artefacts (e.g. .sass-cache and node_modules are excluded by the .dockerignore file)
# Use empty react_local_settings just so the build will work, the correct version gets mounted at runtime
WORKDIR /tmp/build/reimp
RUN mkdir -p /tmp/build /tmp/build/static_collected
COPY reimp /tmp/build/reimp/
RUN mkdir -p /tmp/build/reimp/src/external_config
RUN touch /tmp/build/reimp/src/external_config/react_local_settings.js
RUN npm install
RUN npm run build
RUN npm install -g yuglify
RUN rm /tmp/build/reimp/src/external_config/react_local_settings.js

RUN mkdir -p /opt/imptime/api
WORKDIR /opt/imptime/
RUN mkdir -p logs media

WORKDIR /opt/imptime/api
COPY * /opt/imptime/api/
WORKDIR /opt/imptime/static_collected/

WORKDIR /opt/imptime/api
RUN python manage.py collectstatic --noinput

COPY docker/deploy-static-assets.sh deploy-static-assets.sh

ENTRYPOINT ["./deploy-static-assets.sh"]

