FROM ubuntu:16.04


RUN apt-get update && apt-get install -y --force-yes \
  build-essential \
  curl \
  git \
  wget \
  vim \
  less \
  emacs \
  libpq-dev \
  postgresql \
  python \
  python2.7-dev \
  python-pip \
  libyaml-dev \
  libxml2-dev \
  libjpeg8-dev \
  libpq-dev \
  postgresql \
  python \
  python2.7-dev \
  python-pip \
  libffi-dev \
  libjpeg8-dev
  
RUN mkdir -p /opt/imptime/api
WORKDIR /opt/imptime/
RUN mkdir -p logs

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY version.txt /opt/imptime/api/version.txt
COPY * /opt/imptime/api/

WORKDIR /opt/imptime/api/

COPY docker/start-api.sh start-api.sh
COPY docker/migrate-api-database.sh migrate-api-database.sh
COPY docker/start-dev-api.sh start-dev-api.sh
