FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cron \
    anacron \
    zip \
    vim \
    python \
    git \
    python-pip \
    lftp \
    postgresql-client \
    postgresql-client-common \
    rsync \
    ssh \
    sshpass \
    language-pack-en \
    software-properties-common \
    wget

RUN add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-9.6

RUN pip install --upgrade --force-reinstall pip==10.0.1
RUN pip install awscli --force-reinstall --upgrade

RUN mkdir -p /opt/imptime/

WORKDIR /opt/awscli
RUN git clone --depth 1 -b 1.11.162 https://github.com/aws/aws-cli.git

COPY docker/backup.cron /var/spool/cron/crontabs/root
RUN chmod 0644 /var/spool/cron/crontabs/root
RUN touch /var/log/backup.log

COPY docker/backup.py /opt/imptime/

WORKDIR /opt/awscli/aws-cli

CMD ["cron", "-f"]
