FROM ubuntu:16.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  curl \
  nginx \
  openssl \
  vim

RUN rm /etc/nginx/sites-enabled/*
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/sites-available/* /etc/nginx/sites-available/
WORKDIR /etc/nginx
RUN for f in sites-available/*.conf; do ln -s "/etc/nginx/sites-available/$(basename $f)" "/etc/nginx/sites-enabled/$(basename $f)"; done

RUN mkdir /etc/nginx/ssl

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

RUN openssl req \
    -x509 \
    -nodes \
    -days 365 \
    -newkey \
    rsa:2048 \
    -subj "/CN=*" \
    -keyout /etc/nginx/ssl/certificate.key \
    -out /etc/nginx/ssl/certificate.crt

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
