FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --force-yes \
  build-essential \
  curl \
  git \
  wget \
  vim \
  less \
  emacs \
  libpq-dev \
  postgresql \
  python \
  python2.7-dev \
  python-pip \
  libyaml-dev \
  libxml2-dev \
  libjpeg8-dev \
  libpq-dev \
  postgresql \
  python \
  python2.7-dev \
  python-pip \
  libffi-dev \
  libjpeg8-dev \
  libxslt1-dev

RUN apt-get clean

RUN mkdir -p /opt/imptime/ui
WORKDIR /opt/imptime
RUN mkdir -p logs media

COPY requirements.txt /opt/imptime/ui/

WORKDIR /opt/imptime/ui
RUN pip install -r requirements.txt

WORKDIR /opt/imptime/ui
COPY * /opt/imptime/ui/

COPY docker/start-ui.sh start-ui.sh
COPY docker/start-dev-ui.sh start-dev-ui.sh
COPY docker/start-ui-refresh-listener.sh start-ui-refresh-listener.sh
COPY docker/start-ui-worker.sh start-ui-worker.sh

WORKDIR /opt/imptime/ui