FROM imptime/base:latest

# Build
# Note: build artefacts (e.g. .sass-cache and node_modules are excluded by the .dockerignore file)
# Use empty react_local_settings just so the build will work, the correct version gets mounted at runtime
WORKDIR /tmp/build/reimp
RUN mkdir -p /tmp/build /tmp/build/static_collected
COPY reimp /tmp/build/reimp/
RUN mkdir -p /tmp/build/reimp/src/external_config
RUN touch /tmp/build/reimp/src/external_config/react_local_settings.js
RUN npm install
RUN npm run build
RUN npm install -g yuglify
RUN rm /tmp/build/reimp/src/external_config/react_local_settings.js

RUN mkdir -p /opt/imptime/api
WORKDIR /opt/imptime/
RUN mkdir -p logs media

WORKDIR /opt/imptime/api
COPY * /opt/imptime/api/
WORKDIR /opt/imptime/static_collected/

RUN pip install Pillow==6.2.2 pilkit==1.1.13 Twisted==20.3.0

WORKDIR /opt/imptime/api
RUN python manage.py collectstatic --noinput

COPY docker/deploy-static-assets.sh deploy-static-assets.sh

ENTRYPOINT ["./deploy-static-assets.sh"]

