FROM ubuntu:16.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  curl \
  git \
  libjpeg-dev \
  libxml2-dev \
  libxslt1-dev \
  nodejs-legacy \
  npm \
  python-dev \
  python-pip \
  postgresql-server-dev-9.5 \
  vim

RUN mkdir -p /opt/imptime/
WORKDIR /opt/imptime/
RUN mkdir -p logs
COPY src src


#COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

#WORKDIR /opt/bundlebrat/src


COPY docker/start-django.sh start-django.sh
COPY docker/start-daphne-worker.sh start-daphne-worker.sh
COPY docker/start-migrate.sh start-migrate.sh

ENTRYPOINT ["./start-django.sh"]
