FROM ubuntu:18.04

ENV TZ=UTC

RUN apt-get update && apt-get install -y --force-yes \
  build-essential \
  autoconf \
  curl \
  emacs \
  nano \
  git \
  wget \
  vim \
  less \
  libpq-dev \
  postgresql \
  python \
  python2.7-dev \
  python-pip \
  zlib1g-dev \
  libyaml-dev \
  libxml2-dev \
  libjpeg8-dev \
  libffi-dev \
  libxslt1-dev \
  libxslt-dev \
  libreadline-dev \
  libssl-dev \
  chrpath \
  libxft-dev \
  libfreetype6-dev \
  libfreetype6 \
  libfontconfig1-dev \
  libfontconfig1
  
# Install node
RUN echo "bump docker cache"
RUN curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh && bash nodesource_setup.sh && DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

# Lock to this version, see https://github.com/npm/npm/issues/19989
RUN npm install -g npm@5.6.0

# Build sassc
WORKDIR /tmp/
RUN git clone https://github.com/sass/sassc.git --branch 3.4.0 --depth 1
RUN git clone https://github.com/sass/libsass.git --branch 3.4.0 --depth 1
WORKDIR /tmp/sassc
RUN export SASS_LIBSASS_PATH="/tmp/libsass" && make
RUN export SASS_LIBSASS_PATH="/tmp/libsass" && make install

RUN mkdir -p /opt/imptime/api
WORKDIR /opt/imptime/
RUN mkdir -p logs

COPY requirements.txt .
RUN python -m pip uninstall pip && apt install -y python-pip --reinstall
RUN 
RUN pip install --no-deps -r requirements.txt


