version: '2'

volumes:
  static-assets:

services:

  daphne-worker-1:
    image: imptime/django
    depends_on:
      - redis
    entrypoint: ./start-daphne-worker.sh
    volumes:
     - ../external_config/:/opt/imptime/src/implicitdesign/external_config/

  django:
    image: imptime/django
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
     - ../external_config/:/opt/imptime/src/implicitdesign/external_config/

  django-migrate:
    image: imptime/django
    entrypoint: ./start-migrate.sh
    volumes:
     - ../external_config/:/opt/imptime/src/implicitdesign/external_config/

  nginx:
    image: imptime/nginx
    ports:
     - "80:80"
     - "443:443"
     - "8443:8443"
    depends_on:
      - django
    volumes:
      - static-assets:/opt/imptime/static-assets

  react-static-assets-deployer:
    image: imptime/react-static-assets-deployer
    volumes:
      - static-assets:/opt/imptime/static-assets
      - ../external_config/:/opt/imptime/reimp/external_config/

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"



