FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --force-yes build-essential curl git wget vim emacs

# Intall node
RUN curl -sL https://deb.nodesource.com/setup_4.x -o nodesource_setup.sh && bash nodesource_setup.sh && DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

WORKDIR /opt/imptime/api
COPY docker/start-dev-ui-react-and-css-builder.sh start-dev-ui-react-and-css-builder.sh
ENTRYPOINT ["./start-dev-ui-react-and-css-builder.sh"]
