version: '2'

volumes:
  static-assets:

services:

  daphne-worker-1:
    image: imptime/django-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-django-local-sources
    entrypoint: ./start-daphne-worker-local-sources.sh
    volumes:
     - ../:/opt/imptime

  daphne-worker-2:
    image: imptime/django-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-django-local-sources
    entrypoint: ./start-daphne-worker-local-sources.sh
    volumes:
     - ../:/opt/imptime

  django:
    image: imptime/django-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-django-local-sources
    volumes:
     - ../:/opt/imptime

  django-migrate:
    image: imptime/django-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-django-local-sources
    entrypoint: ./start-migrate-local-sources.sh
    volumes:
     - ../:/opt/imptime
     - ../external_config/:/opt/imptime/src/implicitdesign/external_config/

  nginx:
    image: imptime/nginx-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-nginx-local-sources
    volumes:
      - ../:/opt/imptime

  react-static-assets-deployer:
    image: imptime/react-static-assets-deployer-local-sources
    build:
      context: ../
      dockerfile: docker/Dockerfile-react-static-assets-deployer-local-sources
    volumes:
      - ../:/opt/imptime

