FROM imptime/base:latest

# Needed for puppeteer
# RUN apt-get update && apt-get install -y --force-yes \
#   libnss3 \
#   libx11-xcb1 \
#   libxcursor1 \
#   libcups2 \
#   libxss1 \
#   libffi-dev \
#   cargo

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev \
    pkg-config \
    libnss3 \
    libx11-xcb1 \
    libxcursor1 \
    libcups2 \
    libxss1 \
    cargo && \
    rm -rf /var/lib/apt/lists/*

# phantomjs
RUN wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
RUN ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/

RUN npm install lodash commander puppeteer@19

COPY * /opt/imptime/api/

WORKDIR /opt/imptime/api/


COPY docker/start-api.sh start-api.sh
COPY docker/migrate-api-database.sh migrate-api-database.sh
COPY docker/start-dev-api.sh start-dev-api.sh
COPY docker/start-ui-refresh-listener.sh start-ui-refresh-listener.sh
COPY docker/start-ui-worker.sh start-ui-worker.sh
COPY docker/create_issues_from_incoming_email.sh create_issues_from_incoming_email.sh

COPY version.txt /opt/imptime/api/version.txt
