FROM ubuntu:16.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  nginx \
  openssl \
  vim \
  emacs

RUN rm /etc/nginx/sites-enabled/*
COPY docker/nginx.conf /etc/nginx/sites-available/imptime.conf
COPY docker/nginx_port_based_access.conf /etc/nginx/sites-available/imptime_port_based_access.conf
COPY docker/nginx_dev.conf /etc/nginx/sites-available/imptime_dev.conf

RUN ln -s /etc/nginx/sites-available/imptime.conf /etc/nginx/sites-enabled/imptime.conf
RUN ln -s /etc/nginx/sites-available/imptime_port_based_access.conf /etc/nginx/sites-enabled/imptime_port_based_access.conf

# __token_imptime_dev_conf__

WORKDIR /opt/imptime
COPY docker/reload-nginx.sh /opt/imptime

RUN mkdir /etc/nginx/ssl

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
