# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import colorful.fields
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(help_text=b'Enter a short code to describe the type of activity that took place.', unique=True, max_length=5)),
                ('name', models.CharField(help_text=b'Now enter a more meaningful name for the activity.', max_length=50)),
                ('billable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=255)),
                ('activities', models.ManyToManyField(related_name='activity_group', to='timepiece.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAllocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(max_length=32, choices=[(b'project-type', b'Project Type'), (b'project-status', b'Project Status')])),
                ('label', models.CharField(max_length=255)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True, choices=[(-20, -20), (-19, -19), (-18, -18), (-17, -17), (-16, -16), (-15, -15), (-14, -14), (-13, -13), (-12, -12), (-11, -11), (-10, -10), (-9, -9), (-8, -8), (-7, -7), (-6, -6), (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('enable_timetracking', models.BooleanField(default=False, help_text=b'Enable time tracking functionality for projects with this type or status.')),
                ('billable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, blank=True)),
                ('slug', models.SlugField(unique=True, max_length=255, blank=True)),
                ('email', models.EmailField(max_length=254, blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(max_length=32, blank=True)),
                ('sync_with', models.CharField(blank=True, max_length=100, null=True, choices=[(b'jira', b'Jira')])),
                ('invoice_method', models.CharField(default=b'billable_hours_per_sprint', max_length=50, choices=[(b'billable_hours_per_sprint', b'Billable Hours per Sprint'), (b'billable_hours_per_month', b'Billable Hours per Month'), (b'fixed_quote', b'Fixed quote'), (b'free', b'Free or Equity or Other')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comment', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(related_name='business_comments', to='timepiece.Business')),
                ('modified_by', models.ForeignKey(related_name='business_comments_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filename', models.CharField(max_length=255)),
                ('doc', models.FileField(upload_to=b'project_documents')),
                ('doc_type', models.CharField(max_length=100, choices=[(b'invoice', b'Invoice'), (b'summary', b'Sprint summary'), (b'proposal', b'Sprint proposal'), (b'contract', b'Contract'), (b'other', b'Other')])),
                ('mime_type', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255, db_index=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('original_content', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(related_name='documents', to='timepiece.Business')),
                ('created_by', models.ForeignKey(related_name='business_document_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(related_name='business_document_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('business_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(null=True, blank=True)),
                ('after', models.TextField(null=True, blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('can_view_project_card', models.BooleanField(default=True, verbose_name=b'Can View Sprint Card')),
                ('can_edit_issues', models.BooleanField(default=True, verbose_name=b'Can Edit Issues')),
                ('can_view_issues', models.BooleanField(default=True, verbose_name=b'Can View Issues')),
                ('can_edit_issue_states', models.BooleanField(default=True, verbose_name=b'Can Edit Issue States')),
                ('can_edit_project_states', models.BooleanField(default=True, verbose_name=b'Can Edit Sprint States')),
                ('can_add_issue', models.BooleanField(default=True, verbose_name=b'Can Add Issue')),
                ('can_delete_issue', models.BooleanField(default=True, verbose_name=b'Can Delete Issue')),
                ('can_edit_description', models.BooleanField(default=True, verbose_name=b'Can Edit Description')),
                ('can_add_issue_comment', models.BooleanField(default=True, verbose_name=b'Can Add Issue Comment')),
                ('can_edit_subject', models.BooleanField(default=True, verbose_name=b'Can Edit Subject')),
                ('can_edit_feature', models.BooleanField(default=True, verbose_name=b'Can Edit Feature')),
                ('can_create_sprint', models.BooleanField(default=True, verbose_name=b'Can Create Sprint')),
                ('can_assign_user', models.BooleanField(default=True, verbose_name=b'Can Assign User')),
                ('can_be_scheduled', models.BooleanField(default=False, verbose_name=b'Can Be Scheduled')),
                ('can_view_business_comments', models.BooleanField(default=False, verbose_name=b'Can view project comments')),
                ('can_view_actual_hours', models.BooleanField(default=False, verbose_name=b'Can View Actual Hours')),
                ('can_see_other_user_points', models.BooleanField(default=False, verbose_name=b"Can See Other User's Points")),
                ('can_estimate_own_points', models.BooleanField(default=False, verbose_name=b'Can Estimate Own Points')),
                ('can_view_calendar', models.BooleanField(default=False, verbose_name=b'Can View Calendar')),
                ('can_import_actual_hours', models.BooleanField(default=False, verbose_name=b'Can Import Actual Hours')),
                ('can_edit_business_comments', models.BooleanField(default=False, verbose_name=b'Can edit project comments')),
                ('can_do_dev_checklist', models.BooleanField(default=False, verbose_name=b'Do dev checklist')),
                ('can_do_traffic_checklist', models.BooleanField(default=False, verbose_name=b'Traffic checklist')),
                ('can_do_finance_checklist', models.BooleanField(default=False, verbose_name=b'Finance checklist')),
                ('can_edit_permissions', models.BooleanField(default=False, verbose_name=b'Can Edit Permissions')),
                ('can_toggle_graphs', models.BooleanField(default=False, verbose_name=b'Can Toggle Graphs')),
                ('can_edit_project_detail', models.BooleanField(default=False, verbose_name=b'Can Edit Sprint Detail')),
                ('can_edit_deadlines', models.BooleanField(default=False, verbose_name=b'Can Edit Deadlines ')),
                ('can_view_deadlines', models.BooleanField(default=False, verbose_name=b'Can View Deadlines ')),
                ('can_edit_budget', models.BooleanField(default=False, verbose_name=b'Can Edit Budget ')),
                ('can_view_budget', models.BooleanField(default=False, verbose_name=b'Can View Budget')),
                ('can_edit_invoices', models.BooleanField(default=False, verbose_name=b'Can Edit Invoices')),
                ('can_view_invoices', models.BooleanField(default=False, verbose_name=b'Can View Invoices')),
                ('can_edit_quotes', models.BooleanField(default=False, verbose_name=b'Can Edit Quotes')),
                ('can_view_quotes', models.BooleanField(default=False, verbose_name=b'Can View Quotes')),
                ('can_edit_ctc_billable_rates', models.BooleanField(default=False, verbose_name=b'Can Edit Ctc Billable')),
                ('can_view_ctc_billable_rates', models.BooleanField(default=False, verbose_name=b'Can View Ctc Billable')),
                ('can_view_ctc_rates', models.BooleanField(default=False, verbose_name=b'Can View Ctc')),
                ('can_view_documents', models.BooleanField(default=False, verbose_name=b'Can View Docs')),
                ('can_edit_calendar', models.BooleanField(default=False, verbose_name=b'Can Edit Calendar')),
                ('business', models.ForeignKey(related_name='business_permissions', to='timepiece.Business')),
                ('user', models.ForeignKey(related_name='business_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('hours', models.DecimalField(default=2.0, max_digits=4, decimal_places=2, db_index=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('event_type', models.CharField(default=b'planned', max_length=50, choices=[(b'planned', b'Planned'), (b'meeting', b'Meeting'), (b'leave', b'Leave'), (b'sickday', b'Sick day'), (b'office_closed', b'Office Closed'), (b'personal', b'Personal'), (b'deadline', b'Deadline')])),
                ('status', models.CharField(default=b'ready', max_length=50, choices=[(b'ready', b'Ready'), (b'done', b'Done'), (b'cancelled', b'Cancelled')])),
                ('send_invites_to', models.TextField(null=True, blank=True)),
                ('caldav_uid', models.CharField(max_length=100, null=True, blank=True)),
                ('business', models.ForeignKey(related_name='calendar_events', blank=True, to='timepiece.Business', null=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, blank=True)),
                ('code', models.CharField(max_length=100, blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.FileField(null=True, upload_to=b'logos', blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAssignment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('min_hours_per_week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
            ],
            options={
                'ordering': ('end_date',),
            },
        ),
        migrations.CreateModel(
            name='DevChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('passed', models.BooleanField(default=False, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(to='timepiece.Business', blank=True)),
                ('created_by', models.ForeignKey(related_name='dev_checklist_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(related_name='dev_checklist_modified_by', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevChecklistItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('msg', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev_checklist', models.ForeignKey(related_name='items', blank=True, to='timepiece.DevChecklist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default=b'unverified', max_length=24, choices=[(b'unverified', b'Unverified'), (b'verified', b'Verified'), (b'approved', b'Approved'), (b'invoiced', b'Invoiced'), (b'not-invoiced', b'Not Invoiced')])),
                ('source', models.CharField(max_length=20, choices=[(b'quick_clocker', b'Quick clocker'), (b'emacs', b'Emacs importer'), (b'excel', b'In-site Excel importer')])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(db_index=True, null=True, blank=True)),
                ('seconds_paused', models.PositiveIntegerField(default=0)),
                ('pause_time', models.DateTimeField(null=True, blank=True)),
                ('comments', models.TextField(blank=True)),
                ('extended_comments', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(related_name='entries', to='timepiece.Activity')),
                ('created_by', models.ForeignKey(related_name='entries_created_by', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'permissions': (('can_clock_in', 'Can use Pendulum to clock in'), ('can_pause', 'Can pause and unpause log entries'), ('can_clock_out', 'Can use Pendulum to clock out'), ('view_entry_summary', 'Can view entry summary page'), ('view_payroll_summary', 'Can view payroll summary page')),
            },
        ),
        migrations.CreateModel(
            name='EntryGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(default=b'invoiced', max_length=24, choices=[(b'invoiced', b'Invoiced'), (b'not-invoiced', b'Not Invoiced')])),
                ('number', models.CharField(max_length=50, null=True, verbose_name=b'Reference #', blank=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(null=True, blank=True)),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(default=0, max_digits=8, decimal_places=0)),
                ('description', models.CharField(max_length=255, null=True, blank=True)),
                ('paid', models.BooleanField()),
            ],
            options={
                'permissions': (('view_expense', 'Can view expenses.'),),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('business', models.ForeignKey(related_name='features', to='timepiece.Business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('passed', models.BooleanField(default=False, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(to='timepiece.Business', blank=True)),
                ('created_by', models.ForeignKey(related_name='finance_checklist_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(related_name='finance_checklist_modified_by', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceChecklistItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('msg', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finance_checklist', models.ForeignKey(related_name='items', blank=True, to='timepiece.FinanceChecklist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('applies_on', models.DateField(null=True, blank=True)),
                ('name', models.CharField(default=b'public holiday', max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=255)),
                ('order', models.PositiveIntegerField(unique=True, null=True, blank=True)),
                ('activities', models.ManyToManyField(related_name='activity_bundle', to='timepiece.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(default=0, max_digits=8, decimal_places=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(max_length=255, choices=[(b'new', b'new'), (b'devdone', b'dev_done'), (b'in_internal_qa', b'internal qa'), (b'internal_qa_passed', b'internal qa passed'), (b'in_client_qa', b'external qa'), (b'client_qa_passed', b'external qa passed'), (b'reopened', b'reopened'), (b'onhold', b'on hold'), (b'bug', b'bug'), (b'to be estimated', b'to be estimated'), (b'needscodereview', b'needs code review'), (b"can't reproduce", b"can't reproduce"), (b'discuss with client', b'discuss with client'), (b'dev unclear', b'dev unclear'), (b'duplicate', b'duplicate'), (b'to be designed', b'to be designed'), (b'imported', b'imported'), (b'management', b'management'), (b'quick_clocker', b'quick clocker')])),
                ('number', models.IntegerField(db_index=True, null=True, blank=True)),
                ('subject', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('story_points', models.FloatField(null=True, blank=True)),
                ('order', models.BigIntegerField(null=True, blank=True)),
                ('order2', models.CharField(default=None, max_length=50, null=True, blank=True)),
                ('interface_plugin_number', models.CharField(max_length=255, null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default=None, null=True, blank=True)),
                ('auto_created_during_import', models.BooleanField(default=False)),
                ('adhoc', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(related_name='assigned_issues', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('feature', models.ForeignKey(related_name='issues', blank=True, to='timepiece.Feature', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('attachment', models.FileField(upload_to=b'issue_attachments')),
                ('name', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(related_name='attachments', to='timepiece.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(related_name='comments', to='timepiece.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('issue_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(null=True, blank=True)),
                ('after', models.TextField(null=True, blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuePoints',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('points', models.FloatField(null=True, blank=True)),
                ('issue', models.ForeignKey(related_name='issue_points', to='timepiece.Issue')),
                ('user', models.ForeignKey(related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('business', models.ForeignKey(related_name='stati', to='timepiece.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=255)),
                ('slug', models.CharField(unique=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSchedule',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hours_per_week', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(null=True, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=255, null=True, blank=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('budget', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('tracker_url', models.CharField(default=b'', max_length=255, blank=True)),
                ('billable', models.BooleanField(default=False)),
                ('quote_uncertainty', models.FloatField(default=0.25, null=True, verbose_name=b'Uncertainty overhead as a decimal between 0 and 1', blank=True)),
                ('status2', models.CharField(default=b'pending', max_length=100, db_index=True, choices=[(b'gathering specs', b'gathering specs'), (b'quote sent', b'quote sent'), (b'pending', b'pending'), (b'hopeful', b'hopeful'), (b'in dev', b'in development'), (b'in client qa', b'in client qa'), (b'waiting to invoice', b'waiting to invoice'), (b'invoiced', b'invoiced'), (b'waiting to close', b'waiting to close'), (b'on hold', b'on hold'), (b'closed', b'closed')])),
                ('description', models.TextField(db_index=True, null=True, blank=True)),
                ('short_description', models.CharField(db_index=True, max_length=50, null=True, blank=True)),
                ('order', models.BigIntegerField(null=True, blank=True)),
                ('interface_plugin_number', models.CharField(max_length=255, null=True, blank=True)),
                ('start_dev_at', models.DateField(null=True, blank=True)),
                ('start_internal_qa_at', models.DateField(null=True, blank=True)),
                ('start_client_qa_at', models.DateField(null=True, blank=True)),
                ('invoice_at', models.DateField(null=True, blank=True)),
                ('ratio_management', models.FloatField(default=0.2, verbose_name=b'Ratio of management per develpment hour, between 0 and 1')),
                ('ratio_testing', models.FloatField(default=0.2, verbose_name=b'Ratio of testing per development hour, between 0 and 1')),
                ('ratio_scope_creep', models.FloatField(default=0.25, verbose_name=b'Ratio of additional issue hours added, between 0 and 1')),
                ('colour', colorful.fields.RGBColorField(null=True, blank=True)),
                ('activity_group', models.ForeignKey(related_name='activity_group', verbose_name=b'restrict activities to', blank=True, to='timepiece.ActivityGroup', null=True)),
                ('business', models.ForeignKey(related_name='new_business_projects', to='timepiece.Business')),
                ('point_person', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(related_name='projects_with_status', to='timepiece.Attribute')),
                ('type', models.ForeignKey(related_name='projects_with_type', to='timepiece.Attribute')),
            ],
            options={
                'ordering': ('name', 'status', 'type'),
                'permissions': (('view_project', 'Can view project'), ('email_project_report', 'Can email project report'), ('view_project_time_sheet', 'Can view project time sheet'), ('export_project_time_sheet', 'Can export project time sheet'), ('generate_project_invoice', 'Can generate project invoice')),
            },
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('status', models.CharField(default=b'upcomming', max_length=32, choices=[(b'upcoming', b'Upcoming'), (b'current', b'Current'), (b'complete', b'Complete')])),
                ('project', models.ForeignKey(related_name='contracts', to='timepiece.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('week_start', models.DateField(verbose_name=b'start of week')),
                ('hours', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(to='timepiece.Project')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project hours entry',
                'verbose_name_plural': 'project hours entries',
            },
        ),
        migrations.CreateModel(
            name='ProjectRelationship',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('project', models.ForeignKey(related_name='project_relationships', to='timepiece.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('billable_amount', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('velocity', models.FloatField(default=1)),
                ('work_ratio', models.FloatField(default=0)),
                ('time_tracking_mode', models.CharField(default=b'developer', max_length=50, choices=[(b'developer', b'Developer'), (b'manager', b'Manager'), (b'tester', b'Tester')])),
                ('project', models.ForeignKey(related_name='rate', to='timepiece.Project')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedmineToTimepieceBusinessMapping',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('redmine_business_name', models.CharField(max_length=255)),
                ('timepiece_business_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedmineToTimepieceProjectMapping',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timepiece_business_name', models.CharField(max_length=255)),
                ('redmine_project_code', models.CharField(max_length=255)),
                ('timepiece_project_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=255)),
                ('slug', models.CharField(unique=True, max_length=255, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('date', models.DateField(verbose_name=b'month')),
                ('paye', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('uif', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('bonus', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('expenses', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('leave_accrued', models.DecimalField(default=0, verbose_name=b'Leave accrued this month', max_digits=8, decimal_places=2)),
                ('leave_taken', models.DecimalField(default=0, verbose_name=b'Leave taken this month', max_digits=8, decimal_places=2)),
                ('sick_days', models.DecimalField(default=0, verbose_name=b'Sick days taken this month', max_digits=8, decimal_places=2)),
                ('locked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scheduled_date', models.DateField()),
                ('num_hours', models.IntegerField()),
                ('business', models.ForeignKey(to='timepiece.Business')),
                ('user', models.ForeignKey(related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(null=True, blank=True)),
                ('passed', models.BooleanField(default=False, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(to='timepiece.Business', blank=True)),
                ('created_by', models.ForeignKey(related_name='traffic_checklist_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(related_name='traffic_checklist_modified_by', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficChecklistItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('msg', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, to='timepiece.Issue', null=True)),
                ('project', models.ForeignKey(blank=True, to='timepiece.Project', null=True)),
                ('traffic_checklist', models.ForeignKey(related_name='items', blank=True, to='timepiece.TrafficChecklist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notification_type', models.CharField(max_length=50, choices=[(b'daily_calendar', b'Daily Calendar'), (b'planned_for_today', b'Planned for today')])),
                ('applies_on', models.DateField(null=True, blank=True)),
                ('msg', models.TextField(null=True, blank=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('billable_amount', models.DecimalField(default=0, max_digits=8, decimal_places=2)),
                ('project_names_to_ignore', models.TextField(blank=True)),
                ('authenticate_token', models.CharField(help_text=b'Authentication token remote connections', max_length=100, null=True, blank=True)),
                ('user', models.OneToOneField(related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='types',
            field=models.ManyToManyField(related_name='project_relationships', to='timepiece.RelationshipType', blank=True),
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='user',
            field=models.ForeignKey(related_name='project_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='user_projects', through='timepiece.ProjectRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(related_name='issues', to='timepiece.Project'),
        ),
        migrations.AddField(
            model_name='financechecklistitem',
            name='issue',
            field=models.ForeignKey(blank=True, to='timepiece.Issue', null=True),
        ),
        migrations.AddField(
            model_name='financechecklistitem',
            name='project',
            field=models.ForeignKey(blank=True, to='timepiece.Project', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(related_name='expense', blank=True, to='timepiece.Project', null=True),
        ),
        migrations.AddField(
            model_name='entrygroup',
            name='project',
            field=models.ForeignKey(related_name='entry_group', to='timepiece.Project'),
        ),
        migrations.AddField(
            model_name='entrygroup',
            name='user',
            field=models.ForeignKey(related_name='entry_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_group',
            field=models.ForeignKey(related_name='entries', on_delete=django.db.models.deletion.SET_NULL, blank=True, to='timepiece.EntryGroup', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='issue',
            field=models.ForeignKey(related_name='entries', blank=True, to='timepiece.Issue', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(related_name='entries', to='timepiece.Location'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(related_name='timepiece_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devchecklistitem',
            name='issue',
            field=models.ForeignKey(blank=True, to='timepiece.Issue', null=True),
        ),
        migrations.AddField(
            model_name='devchecklistitem',
            name='project',
            field=models.ForeignKey(blank=True, to='timepiece.Project', null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='contract',
            field=models.ForeignKey(related_name='milestones', to='timepiece.ProjectContract'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='contract',
            field=models.ForeignKey(related_name='assignments', to='timepiece.ProjectContract'),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='user',
            field=models.ForeignKey(related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='project',
            field=models.ForeignKey(related_name='documents', blank=True, to='timepiece.Project', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('type', 'label')]),
        ),
        migrations.AddField(
            model_name='assignmentallocation',
            name='assignment',
            field=models.ForeignKey(related_name='blocks', to='timepiece.ContractAssignment'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrelationship',
            unique_together=set([('user', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='projecthours',
            unique_together=set([('week_start', 'project', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='issuestatus',
            unique_together=set([('name', 'business')]),
        ),
        migrations.AlterUniqueTogether(
            name='issuepoints',
            unique_together=set([('user', 'issue')]),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('name', 'business')]),
        ),
        migrations.AlterUniqueTogether(
            name='contractassignment',
            unique_together=set([('contract', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='businesspermissions',
            unique_together=set([('user', 'business')]),
        ),
    ]
