# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0020_auto_20161208_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 11, 10, 49, 48, 166060)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
