# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0023_auto_20170116_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='point_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
