# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0024_auto_20170118_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='point_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
