# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0025_auto_20170118_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_with_status', to='timepiece.Attribute'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_with_type', to='timepiece.Attribute'),
        ),
    ]
