# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0027_auto_20170124_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 24, 14, 3, 26, 322891)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuetag',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 24, 14, 3, 33, 963409)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 24, 14, 3, 36, 970679)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
