# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0028_auto_20170124_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuetag',
            unique_together=set([('issue', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'category')]),
        ),
    ]
