# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0029_auto_20170124_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
