# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:14
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Project = apps.get_model('timepiece.Project')

    last_business_id = None
    for p in Project.objects.all().order_by("business_id", "pk"):
        if p.business_id != last_business_id:
            last_business_id = p.business_id
            number = 1
        p.number = number
        number += 1
        p.save()


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0030_project_number'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
