# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0031_set_project_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='can_group_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_children', to='timepiece.Issue'),
        ),
    ]
