# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0032_auto_20170125_1028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuetag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='issuetag',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuetag',
            name='tag',
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', to='timepiece.Tag'),
        ),
        migrations.DeleteModel(
            name='IssueTag',
        ),
    ]
