# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0033_auto_20170126_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timepiece.Activity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timepiece.Location'),
        ),
    ]
