# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0034_auto_20170127_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueattachment',
            options={'default_permissions': []},
        ),
        migrations.AddField(
            model_name='issueattachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 3, 22, 6, 12, 533102)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueattachment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueattachment',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 3, 22, 6, 15, 873576)),
            preserve_default=False,
        ),
    ]
