# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0035_auto_20170203_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueattachment',
            name='content_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
