# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0036_issueattachment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status2',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='timepiece.IssueStatus'),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_statuses', to='timepiece.Business'),
        ),
    ]
