# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0038_insert_default_issue_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='timepiece.Business')),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='status2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='timepiece.IssueStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='status3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timepiece.ProjectStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstatus',
            unique_together=set([('name', 'business')]),
        ),
    ]
