# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:14
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Business = apps.get_model('timepiece.Business')
    ProjectStatus = apps.get_model('timepiece.ProjectStatus')
    Project = apps.get_model('timepiece.Project')

    for b in Business.objects.all():

        for status_items in [ ('gathering specs', 'gathering specs'),
                              ('quote sent', 'quote sent'),
                              ('pending', 'pending'),
                              ('hopeful', 'hopeful'), 
                              ('in dev', 'in development'),
                              ('in client qa', 'in client qa'), 
                              ('waiting to invoice', 'waiting to invoice'), 
                              ('invoiced', 'invoiced'), 
                              ('waiting to close', 'waiting to close'),
                              ('on hold', 'on hold'),
                              ('closed', 'closed') ]:

            status_name = status_items[0]
            status3 = ProjectStatus.objects.get_or_create(name=status_name, business=b)[0]
            Project.objects.filter(business=b, status2=status_name).update(status3_id=status3.id)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0039_auto_20170207_2014'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
