# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0040_set_project_status3'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_invite_users',
            field=models.BooleanField(default=False, verbose_name=b'Can Invite Users'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_set_user_permissions',
            field=models.BooleanField(default=False, verbose_name=b'Can Set User Permissions'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='is_active_member_of_business',
            field=models.BooleanField(default=True, verbose_name=b'Is An Active Member of This Business'),
        ),
    ]
