# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0042_business_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_tags',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Tags'),
        ),
    ]
