# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0044_businessinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinvite',
            name='accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='businessinvite',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
