# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:18
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    BusinessPermissions = apps.get_model('timepiece.BusinessPermissions')
    bps = BusinessPermissions.objects.all()
    bps.update(can_view_permissions=True)

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0046_businesspermissions_can_view_permissions'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
