# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0047_give_everyone_view_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 21, 50, 39, 30952)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 21, 50, 42, 98670)),
            preserve_default=False,
        ),
    ]
