# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0048_auto_20170222_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_sprint',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Sprint'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_sprint_status',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Sprint'),
        ),
    ]
