# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0051_auto_20170515_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
