# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0051_auto_20170515_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_view_testables',
            field=models.BooleanField(default=True, verbose_name=b'Can View Testables'),
        ),
    ]
