# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 14:09
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Business = apps.get_model('timepiece.Business')
    IssueStatus = apps.get_model('timepiece.IssueStatus')
    Issue = apps.get_model('timepiece.Issue')

    for b in Business.objects.all():

        for status_items in [ ('new', 'new'),
                             ('devdone', 'dev_done'),
                             ('in_internal_qa', 'internal qa'),
                             ('internal_qa_passed', 'internal qa passed'),
                             ('in_client_qa', 'external qa'),
                             ('client_qa_passed', 'external qa passed'),
                             ('reopened', 'reopened'),
                             ('onhold', 'on hold'),
                             ('bug', 'bug'),
                             ('to be estimated', 'to be estimated'),
                             ('needscodereview', 'needs code review'),
                             ("cannot reproduce", "cannot reproduce"),
                             ("discuss with client", "discuss with client"),
                             ('dev unclear', 'dev unclear'),
                             ('duplicate', 'duplicate'),
                             ('to be designed', 'to be designed'),
                             ('imported', 'imported'),
                             ('management', 'management'),
                             ('quick_clocker', 'quick clocker') ]:

            status_name = status_items[0]
            status2 = IssueStatus.objects.get_or_create(name=status_name, business=b)[0]
            Issue.objects.filter(project__business=b, status=status_name).update(status2_id=status2.id)

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0052_businesspermissions_can_view_testables'),
    ]

    operations = [
    ]
