# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0054_merge_20170821_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 25, 10, 36, 6, 42563)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='doc',
            field=models.FileField(upload_to=lib.fields.UploadTo(b'project_documents')),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=lib.fields.UploadTo(b'logos')),
        ),
        migrations.AlterField(
            model_name='issueattachment',
            name='attachment',
            field=models.FileField(upload_to=lib.fields.UploadTo(b'issue_attachments')),
        ),
    ]
