# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0055_auto_20170825_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='doc',
            field=models.FileField(max_length=255, upload_to=lib.fields.UploadTo(b'project_documents')),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=lib.fields.UploadTo(b'logos')),
        ),
        migrations.AlterField(
            model_name='issueattachment',
            name='attachment',
            field=models.FileField(max_length=255, upload_to=lib.fields.UploadTo(b'issue_attachments')),
        ),
    ]
