# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 16:33
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def forwards(apps, schema_editor):
    Project = apps.get_model('timepiece', 'Project')
    ProjectStatus = apps.get_model('timepiece', 'ProjectStatus')
    for p in Project.objects.exclude(status2=F('status3__name')):
        p.status3 = ProjectStatus.objects.get_or_create(name=p.status2, business=p.business)[0]
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0057_auto_20170906_1225'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
