# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0060_fix_project_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timepiece.ProjectStatus'),
            preserve_default=False,
        ),
    ]
