# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0061_auto_20171025_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'template', b'Template')], default=b'sprint', max_length=20),
        ),
    ]
