# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0062_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'template', b'Template')], db_index=True, default=b'sprint', max_length=20),
        ),
    ]
