# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 16:23
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def forwards(apps, schema_editor):
    Issue = apps.get_model('timepiece', 'Issue')
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    for i in Issue.objects.exclude(status2__name=F('status')):
        i.status2 = IssueStatus.objects.get_or_create(name=i.status, business=i.project.business)[0]
        i.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0063_auto_20171031_2106'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
