# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 16:25
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):

    DEFAULT_ISSUE_STATUS_CHOICES = (
           'new',
           'dev_done',
           'internal qa',
           'internal qa passed',
           'external qa',
           'external qa passed',
           'reopened',
           'on hold',
           'bug',
           'to be estimated',
           'needs code review',
           'dev unclear', 'dev unclear',
           'duplicate',
           'to be designed',
           'imported',
           'management',
           'quick clocker'
        )
    
    Business = apps.get_model('timepiece', 'Business')
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    for b in Business.objects.all():
        for name in DEFAULT_ISSUE_STATUS_CHOICES:
            IssueStatus.objects.get_or_create(name=name, business=b)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0064_fix_issue_status'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
