# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 20:20
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Issue = apps.get_model('timepiece', 'Issue')
    Business = apps.get_model('timepiece', 'Business')
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    mapping = {
        'quick_clocker': 'quick clocker',
        'internal_qa_passed': 'internal qa passed',
        'in_client_qa': 'in client qa',
        'in_internal_qa': 'in internal qa',
        'dev_done': 'dev done',
        'client_qa_passed': 'client qa passed',
        'devdone': 'dev done',
        'internal_qa': 'in internal qa',
        'onhold': 'on hold',
        'needscodereview': 'needs code review'
    }
    for before, after in mapping.items():
        for b in Business.objects.all():
            old_issue_status = IssueStatus.objects.filter(name=before, business=b).first()
            if old_issue_status:
                new_issue_status = IssueStatus.objects.get_or_create(name=after, business=b)[0]
                Issue.objects.filter(project__business=b, status2=old_issue_status).update(status2=new_issue_status)
                old_issue_status.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0066_remove_issue_status'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
