# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0068_issue_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitygroup',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='assignmentallocation',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='businesscomment',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='businessdocument',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='businesshistory',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='entrygroup',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='hourgroup',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='issuehistory',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='personschedule',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='projectcontract',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='redminetotimepiecebusinessmapping',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='redminetotimepieceprojectmapping',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'default_permissions': []},
        ),
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 32, 471504)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 35, 407640)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentallocation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 38, 671739)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentallocation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentallocation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 41, 839603)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='business',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 44, 247594)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 47, 367548)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businesshistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 51, 303783)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesshistory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesshistory',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 28, 58, 751208)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 0, 119482)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 1, 615464)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractassignment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 3, 54972)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devchecklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 4, 591165)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devchecklist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devchecklist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devchecklistitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 5, 791705)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devchecklistitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devchecklistitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entrygroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 6, 919323)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 7, 974821)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financechecklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 9, 751369)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financechecklist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financechecklist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financechecklistitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 11, 7342)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financechecklistitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financechecklistitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 11, 967420)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hourgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 12, 878841)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourgroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hourgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 13, 815144)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 14, 727150)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuepoints',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 15, 686830)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuepoints',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuepoints',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 16, 622960)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personschedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 17, 727156)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personschedule',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 18, 935102)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecthours',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 20, 39054)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthours',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecthours',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 21, 119023)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 22, 151109)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 23, 422747)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='redminetotimepiecebusinessmapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 24, 383057)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redminetotimepiecebusinessmapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redminetotimepiecebusinessmapping',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='redminetotimepieceprojectmapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 25, 294931)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redminetotimepieceprojectmapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redminetotimepieceprojectmapping',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 26, 158890)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 27, 102953)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 28, 14926)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficchecklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 28, 902750)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficchecklist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficchecklist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trafficchecklistitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 29, 790840)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficchecklistitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficchecklistitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 30, 686231)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotification',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 10, 29, 31, 878945)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
