# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0069_auto_20171103_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIssueOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('issue', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timepiece.Issue')),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
