# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 14:02
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone

def forwards(apps, schema_editor):
    Project = apps.get_model('timepiece', 'Project')
    ProjectIssueOrder = apps.get_model('timepiece', 'ProjectIssueOrder')

    for p in Project.objects.all():
        new_world_order = [ ProjectIssueOrder(project=p, issue_id=i['id'], order=i['order'] or 0.0, created=timezone.now(), modified=timezone.now())
                            for i in p.issues.all().order_by("order").values("id", "order") ]
        ProjectIssueOrder.objects.bulk_create(new_world_order)

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0070_projectissueorder'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),        
    ]
