# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0071_copy_issue_ordering_to_new_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='order',
            new_name='order_deprecated',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='order2',
        ),
    ]
