# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 15:32
from __future__ import unicode_literals
from django.db.models import Count

from django.db import migrations

def forwards(apps, schema_editor):
    Project = apps.get_model('timepiece', 'Project')
    ProjectIssueOrder = apps.get_model('timepiece', 'ProjectIssueOrder')

    num_deleted = 0
    for project in Project.objects.all():
        with_duplicates = ProjectIssueOrder.objects.filter(project=project).order_by("issue_id").values('issue_id').annotate(count=Count('issue_id')).filter(count__gt=1)
    
        for d in with_duplicates:
            duplicate = ProjectIssueOrder.objects.filter(issue_id=d['issue_id'], project=project)[1]
            duplicate.delete()
            num_deleted+=1
    print("Deleted %d duplicates" % num_deleted)

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0072_auto_20171104_1534'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
