# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0073_delete_duplicate_orderings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectissueorder',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectissueorder',
            unique_together=set([('project', 'issue')]),
        ),
    ]
