# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0074_auto_20171109_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(null=True)),
                ('is_hard_deadline', models.BooleanField()),
                ('represents_project_start', models.BooleanField()),
                ('represents_project_end', models.BooleanField()),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDeadlineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('business', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_types', to='timepiece.Business')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='deadline_type',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timepiece.ProjectDeadlineType'),
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='project',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timepiece.Project'),
        ),
    ]
