# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 16:42
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Business = apps.get_model('timepiece', 'Business')
    ProjectDeadlineType = apps.get_model('timepiece', 'ProjectDeadlineType')

    DEFAULT_PROJECT_DEADLINE_TYPES = ( ('start_dev', 'Start development'),
                                       ('start_internal_qa', 'Start internal QA'),
                                       ('end_external_qa', 'End external QA') )
    
    for b in Business.objects.all():
        for code, name in DEFAULT_PROJECT_DEADLINE_TYPES:
            ProjectDeadlineType.objects.get_or_create(name=name, business=b)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0075_auto_20171110_1642'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
