# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0076_insert_deadline_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeadlinetype',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectdeadlinetype',
            unique_together=set([('name', 'business')]),
        ),
    ]
