# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0077_auto_20171110_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeadline',
            options={'ordering': ('deadline',)},
        ),
        migrations.AddField(
            model_name='projectdeadline',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectdeadline',
            name='project',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='timepiece.Project'),
        ),
    ]
