# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0078_auto_20171110_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_reviewed_at', models.DateTimeField(null=True)),
                ('issue', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='timepiece.Issue')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('review_cycle_days', models.IntegerField(default=14)),
                ('project', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='timepiece.Project')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_review_cycle',
            field=models.BooleanField(default=False, verbose_name=b'Can Edit Review Cycle'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_view_review_cycle',
            field=models.BooleanField(default=False, verbose_name=b'Can View Review Cycle'),
        ),
    ]
