# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0079_auto_20171113_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuereview',
            options={'ordering': ('last_reviewed_at',)},
        ),
        migrations.AddField(
            model_name='issuereview',
            name='review_due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
