# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0080_auto_20171113_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereview',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='timepiece.Issue'),
        ),
        migrations.AlterField(
            model_name='projectissueorder',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Issue'),
        ),
        migrations.AlterField(
            model_name='projectissueorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Project'),
        ),
    ]
