# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0081_auto_20171113_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereview',
            name='auto_recalculate',
            field=models.BooleanField(default=True),
        ),
    ]
