# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0082_issuereview_auto_recalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='review_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='review_cycle_days',
            field=models.IntegerField(),
        ),
    ]
