# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0083_auto_20171114_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectreview',
            unique_together=set([('project', 'review_by')]),
        ),
    ]
