# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0084_auto_20171114_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='must_always_review',
            field=models.BooleanField(default=False),
        ),
    ]
