# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0085_projectreview_must_always_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereview',
            name='auto_recalculate',
        ),
        migrations.RemoveField(
            model_name='issuereview',
            name='review_due_at',
        ),
        migrations.AlterField(
            model_name='issuereview',
            name='last_reviewed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
