# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0086_auto_20171114_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_sprint_type',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Sprint Type'),
        ),
        migrations.AlterField(
            model_name='businesspermissions',
            name='can_edit_sprint_status',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Sprint Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'template', b'Template'), (b'sprinkle', b'Sprinkle'), (b'inbox', b'Inbox')], db_index=True, default=b'sprint', max_length=20),
        ),
    ]
