# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0088_auto_20171116_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='subject_quality_error',
            field=models.TextField(null=True),
        ),
    ]
