# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0090_copy_attachments_to_visual_spec_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProjectOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Business')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepiece.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='businessprojectorder',
            unique_together=set([('business', 'project')]),
        ),
    ]
