# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 15:48
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone

def forwards(apps, schema_editor):
    Business = apps.get_model('timepiece', 'Business')
    Project = apps.get_model('timepiece', 'Project')
    BusinessProjectOrder = apps.get_model('timepiece', 'BusinessProjectOrder')

    for b in Business.objects.all():
        new_world_order = [ BusinessProjectOrder(business=b, project_id=p['id'], order=p['order'] or 0.0, created=timezone.now(), modified=timezone.now())
                            for p in Project.objects.filter(business_id=b.id).order_by("order").values("id", "order") ]
        BusinessProjectOrder.objects.bulk_create(new_world_order)



class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0091_auto_20171128_1548'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),        
    ]
