# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0092_migrate_project_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
    ]
