# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 16:04
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    IssueAttachment = apps.get_model('timepiece', 'IssueAttachment')
    VisualSpecDocument = apps.get_model('imptime', 'VisualSpecDocument')
    VisualSpecProject = apps.get_model('imptime', 'VisualSpecProject')
    VisualSpecIssue = apps.get_model('imptime', 'VisualSpecIssue')

    for issue_attachment in IssueAttachment.objects.all():

        # Skip attachments which were processed before
        if VisualSpecProject.objects.filter(project=issue_attachment.issue.project.business).count() > 0:
            continue
        if VisualSpecIssue.objects.filter(issue=issue_attachment.issue).count() > 0:
            continue

        print("processing attachment " % issue_attachment)
        
        vsd = VisualSpecDocument.objects.create(original_doc=issue_attachment.attachment,
                                                hires_width=100,
                                                hires_height=100,
                                                is_image=False,
                                                name=issue_attachment.name,
                                                content_type=issue_attachment.content_type)
        VisualSpecProject.objects.create(visual_spec_document=vsd,
                                         project=issue_attachment.issue.project.business,
                                         order=1)
        VisualSpecIssue.objects.create(visual_spec_document=vsd,
                                       issue=issue_attachment.issue,
                                       order=1)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0093_remove_project_order'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
