# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0094_migrate_more_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'template', b'Template'), (b'checklist', b'Checklist'), (b'sprinkle', b'Sprinkle'), (b'backlog', b'Backlog'), (b'regression', b'Regression'), (b'audit', b'Audit'), (b'spec', b'Spec'), (b'inbox', b'Inbox')], db_index=True, default=b'sprint', max_length=20),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=b'general', max_length=100),
        ),
    ]
