# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models, IntegrityError

def tag_names_to_lowercase(apps, schema_editor):
    # Convert tags to lowercase and "merge" duplicates
    Tag = apps.get_model('timepiece', 'Tag')

    for tag in Tag.objects.all():
        try:
            tag.name = tag.name.lower()
            tag.save()
        except IntegrityError:
            remaining_tag = Tag.objects.get(category=tag.category, name=tag.name.lower())

            for issue in tag.issues.all():
                issue.tags.remove(tag)
                issue.tags.add(remaining_tag)

            tag.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0095_auto_20171206_1214'),
    ]

    operations = [
        migrations.RunPython(tag_names_to_lowercase, migrations.RunPython.noop)
    ]
