# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0096_tag_name_to_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_delete_project',
            field=models.BooleanField(default=True, verbose_name=b'Can Delete Project'),
        ),
    ]
