# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0097_businesspermissions_can_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='timepiece.Business')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='role',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timepiece.ProjectRole'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set([('name', 'business')]),
        ),
    ]
