# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-10 19:01
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    ProjectRole = apps.get_model('timepiece', 'ProjectRole')
    Business = apps.get_model('timepiece', 'Business')

    DEFAULT_PROJECT_ROLES = ( ('developer', 'developer'),
                              ('manager', 'manager'),
                              ('tester', 'tester') )

    for b in Business.objects.all():
        for code, name in DEFAULT_PROJECT_ROLES:
            ProjectRole.objects.get_or_create(name=name, business=b)
    

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0098_auto_20180210_1901'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
