# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0099_insert_default_project_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('mode_type', models.CharField(choices=[(b'dev_mode', b'Developer'), (b'manager_mode', b'Manager'), (b'finance_mode', b'Finance'), (b'client_mode', b'Client'), (b'tester_mode', b'Tester'), (b'spec_mode', b'Spec')], default=b'dev_mode', max_length=255)),
                ('business', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mode_types', to='timepiece.Business')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectmodetype',
            unique_together=set([('mode_type', 'business')]),
        ),
    ]
