# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 20:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0099_insert_default_project_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='issue',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timepiece.Issue'),
        ),
    ]
