# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0100_auto_20180219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
