# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 21:33
from __future__ import unicode_literals

from django.db import migrations
from timepiece.models import BusinessPermissions, Business
from django.conf import settings
from django.contrib.auth.models import User

def migrate(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0101_auto_20180304_1950'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
