# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0102_assign_all_permission_to_gtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_velocity',
            field=models.BooleanField(default=False, verbose_name=b'Can Edit Velocity'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_view_velocity',
            field=models.BooleanField(default=False, verbose_name=b'Can View Velocity'),
        ),
    ]
