# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0103_auto_20180321_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'issue', b'Issue'), (b'adhoc', b'Adhoc'), (b'correspondence', b'Correspondence')], default=b'issue', max_length=10),
        ),
    ]
