# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 19:39
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Issue = apps.get_model('timepiece', 'Issue')
    Issue.objects.filter(adhoc=True).update(issue_type='adhoc')
    Issue.objects.filter(adhoc=False).update(issue_type='issue')

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0104_issue_issue_type'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
