# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0106_remove_issue_adhoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'issue', b'Issue'), (b'adhoc', b'Adhoc'), (b'correspondence', b'Correspondence')], default=b'issue', max_length=20),
        ),
    ]
