# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 19:17
from __future__ import unicode_literals

from django.db import migrations

from timepiece.models import BusinessPermissions, Business
from django.contrib.auth.models import User


def migrate(apps, schema_editor):

    # We have to use real objects because I want to use the helpers on the timepiece models.
    # This means this migration will become stale over time.
    for user in User.objects.filter(username__in=['us']):
        for business in Business.objects.all():
            BusinessPermissions.give_all_permissions_to_user(user=user, business=business)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0107_auto_20180325_2011'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
