# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0108_update_more_invoice_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='comment_type',
            field=models.CharField(choices=[(b'comment', b'Comment'), (b'annotation', b'Annotation'), (b'timesheet', b'Timesheet'), (b'raw_spec', b'Raw spec')], default=b'comment', max_length=50),
        ),
    ]
