# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0109_issuecomment_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_share_issues',
            field=models.BooleanField(default=True, verbose_name=b'Can Share Issues'),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='comment_type',
            field=models.CharField(choices=[(b'comment', b'Comment'), (b'correspondence', b'Correspondence'), (b'timesheet', b'Timesheet'), (b'raw_spec', b'Raw spec')], default=b'comment', max_length=50),
        ),
    ]
