# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0110_auto_20180328_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='share_ref',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='share_ref_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='share_ref',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='share_ref_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
