# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0111_auto_20180328_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='enriched_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='enriched_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
