# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 20:43
from __future__ import unicode_literals

from django.db import migrations
import re

def forwards(apps, schema_editor):
    Business = apps.get_model('timepiece', 'Business')
    BusinessPermissions = apps.get_model('timepiece', 'BusinessPermissions')
    User = apps.get_model('auth', 'User')

    regex = "My personal project .*\(and I am (.*)\)"
    
    for b in Business.objects.filter(name='me'):
        try:
            primary_user_email = re.findall(regex, b.description)[0]
            primary_user = User.objects.get(email=primary_user_email)
            other_users = BusinessPermissions.objects.filter(business=b).exclude(user=primary_user)
            other_users.delete()
        except IndexError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0112_auto_20180329_1833'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
