# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0113_remove_users_from_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'issue', b'Issue'), (b'adhoc', b'Adhoc'), (b'correspondence', b'Correspondence'), (b'minutes', b'Minutes')], default=b'issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'minutes', b'Minutes'), (b'template', b'Template'), (b'checklist', b'Checklist'), (b'sprinkle', b'Sprinkle'), (b'backlog', b'Backlog'), (b'regression', b'Regression'), (b'audit', b'Audit'), (b'spec', b'Spec'), (b'inbox', b'Inbox')], db_index=True, default=b'sprint', max_length=20),
        ),
    ]
