# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:14
from __future__ import unicode_literals
from dateutil.relativedelta import relativedelta

from django.db import migrations

def migrate(apps, schema_editor):
    CalendarEvent = apps.get_model('timepiece', 'CalendarEvent')
    for event in CalendarEvent.objects.filter(event_type__in=['leave', 'sickday', 'personal', 'office_closed', 'deadline']):
        event.start = event.start + relativedelta(hours=12)
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0114_auto_20180504_1403'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
