# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0115_update day calendar events to midday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectissueorder',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_issue_orders', to='timepiece.Issue'),
        ),
    ]
