# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0116_auto_20180723_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'issue', b'Issue'), (b'adhoc', b'Adhoc'), (b'correspondence', b'Correspondence'), (b'minutes', b'Minutes'), (b'management-assign', b'Assign issues'), (b'management-estimate', b'Estimate issues'), (b'management-testables', b'Create testables'), (b'management-scope', b'Create issues for scoping'), (b'management-general', b'General management')], default=b'issue', max_length=50),
        ),
    ]
