# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-25 14:27
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    Business = apps.get_model('timepiece', 'Business')
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    Issue = apps.get_model('timepiece', 'Issue')

    for business in Business.objects.all():
        new_status = IssueStatus.objects.get(name="blocked",
                                             business=business)
        issue_status_to_change = IssueStatus.objects.filter(name__in=[ "discuss with client", "onhold", "on hold" ],
                                                            business=business)
        Issue.objects.filter(status2__in=issue_status_to_change,
                             project__business_id=business.id)\
                     .update(status2_id=new_status.id)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0118_add_blocked_issue_status'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
