# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-25 14:33
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    IssueStatus.objects.filter(name__in=[ "discuss with client", "onhold", "on hold" ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0119_consolidate_onhold_and_discusswithclient'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
