# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0121_create_waiting_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='risky',
            field=models.BooleanField(default=False),
        ),
    ]
