# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0122_issue_risky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[(b'issue', b'Issue'), (b'adhoc', b'Adhoc'), (b'management-general', b'General management'), (b'management-meeting', b'Create issues for speccing and scoping'), (b'management-spec', b'Create issues for speccing and scoping'), (b'management-finance', b'Performing recons and finance tasks'), (b'management-assign', b'Assign issues'), (b'management-estimate', b'Estimate issues'), (b'management-testables', b'Create testables'), (b'correspondence', b'Correspondence'), (b'minutes', b'Minutes')], default=b'issue', max_length=50),
        ),
    ]
