# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0123_auto_20180726_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='money_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
