# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 18:55
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    IssueHistory = apps.get_model('timepiece', 'IssueHistory')

    fixes = ["added comment", "edited comment", "deleted comment",
             "deleted testable", "added testable", "edited_testable" ]

    for fix in fixes:
        IssueHistory.objects.filter(description__icontains=fix).update(description=fix)

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0124_issuehistory_money_sensitive'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
