# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0125_simply issue history descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_view_issue_history',
            field=models.BooleanField(default=True, verbose_name=b'Can View Issue History'),
        ),
    ]
