# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0126_businesspermissions_can_view_issue_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='original_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='timepiece.Issue'),
        ),
    ]
