# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 20:09
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def migrate(apps, schema_editor):
    IssueHistory = apps.get_model('timepiece', 'IssueHistory')
    Issue = apps.get_model('timepiece', 'Issue')
    IssueHistory.objects.all().filter(issue_id__in=Issue.objects.all()).update(original_issue_id=F('issue_id'))

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0127_issuehistory_original_issue'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
