# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 08:13
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    Business = apps.get_model('timepiece', 'Business')
    IssueStatus = apps.get_model('timepiece', 'IssueStatus')
    for business in Business.objects.all():
        IssueStatus.objects.get_or_create(name='dev in progress',
                                          business_id=business.id)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0128_update issue history original_issue_id'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
