# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0129_create dev in progress issue status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_old_clock_entries',
            field=models.BooleanField(default=False, verbose_name=b'Can Edit Old Clock Entries'),
        ),
    ]
