# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-09 13:24
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def migrate(apps, schema_editor):
    IssueHistory = apps.get_model('timepiece', 'IssueHistory')
    Issue = apps.get_model('timepiece', 'Issue')
    IssueHistory.objects.all().filter(issue_id__in=Issue.objects.all()).update(original_issue_id=F('issue_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0130_businesspermissions_can_edit_old_clock_entries'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
