# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-09 20:05
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    Entry = apps.get_model('timepiece', 'Entry')
    Entry.objects.filter(issue_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0131_fix issue histories'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
