# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0132_delete orphaned entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='needs_issues',
            field=models.ManyToManyField(related_name='issues_needing_us', to='timepiece.Issue'),
        ),
    ]
