# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0133_issue_needs_issues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='business',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='feature',
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
