# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0134_auto_20180919_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_decision_journal',
            field=models.BooleanField(default=False, verbose_name=b'Can Edit Decision Journal'),
        ),
        migrations.AddField(
            model_name='businesspermissions',
            name='can_view_decision_journal',
            field=models.BooleanField(default=False, verbose_name=b'Can View Decision Journal'),
        ),
    ]
