# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0135_auto_20181016_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueattachment',
            name='issue',
        ),
        migrations.DeleteModel(
            name='IssueAttachment',
        ),
    ]
