# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0136_auto_20181026_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Company',
        ),
    ]
