# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timepiece', '0137_auto_20181027_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False, verbose_name=b'Can Invite Users')),
                ('can_set_user_permissions', models.BooleanField(default=False, verbose_name=b'Can Set User Permissions')),
                ('is_active_member_of_company', models.BooleanField(default=True, verbose_name=b'Is An Active Member of This Company')),
                ('can_edit_company_info', models.BooleanField(default=False, verbose_name=b'Can Edit Company Info')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='companypermissions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to='timepiece.Company'),
        ),
        migrations.AddField(
            model_name='companypermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companypermissions',
            unique_together=set([('user', 'company')]),
        ),
    ]
