# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 13:08
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):
    Sprint = apps.get_model('timepiece', 'Project') #sic
    SprintStatus = apps.get_model('timepiece', 'ProjectStatus') #sic

    for sprint in Sprint.objects.all().exclude(project_type__in=['closed']).filter(project_type='spec'):
        new_status = SprintStatus.objects.get_or_create(name='spec', business_id=sprint.business_id)[0]
        sprint.status3 = new_status
        sprint.project_type = 'sprint'
        sprint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0140_auto_20181027_2153'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
