# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-01 08:39
from __future__ import unicode_literals

from django.db import migrations, models

def migrate(apps, schema_editor):
    UserProfile = apps.get_model('timepiece', 'UserProfile')
    for user_profile in UserProfile.objects.all():
        user_profile.is_onboarded = True
        user_profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0141_userotptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
