# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0142_userprofile_is_onboarded'),
        ('timepiece', '0141_move sprint spec type to status'),
    ]

    operations = [
    ]
