# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0143_merge_20181107_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'sprint', b'Sprint'), (b'minutes', b'Minutes'), (b'template', b'Template'), (b'checklist', b'Checklist'), (b'sprinkle', b'Sprinkle'), (b'backlog', b'Backlog'), (b'regression', b'Regression'), (b'audit', b'Audit'), (b'inbox', b'Inbox')], db_index=True, default=b'sprint', max_length=20),
        ),
    ]
