# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0144_auto_20181107_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermissions',
            name='can_edit_issue_feature',
            field=models.BooleanField(default=True, verbose_name=b'Can Edit Issue Feature'),
        ),
    ]
