# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0145_businesspermissions_can_edit_issue_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
