# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 17:17
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    SprintStatus = apps.get_model('timepiece', 'ProjectStatus') #sic
    SprintStatus.objects.filter(name='closed').update(is_closed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0146_projectstatus_is_closed'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
