# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0147_set_closed_sprint_Status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='quote_uncertainty',
            field=models.FloatField(blank=True, default=1.25, null=True, verbose_name=b'Uncertainty overhead as a ratio value. 1 means no uncertainty.'),
        ),
    ]
