# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_attachment', models.FileField(blank=True, max_length=255, null=True, upload_to=lib.fields.UploadTo(b'mail-queue/attachments'))),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='MailerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='Subject')),
                ('to_address', models.TextField(verbose_name='To')),
                ('bcc_address', models.TextField(blank=True, verbose_name='BCC')),
                ('from_address', models.EmailField(max_length=250, verbose_name='From')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML Content')),
                ('app', models.CharField(blank=True, max_length=250, verbose_name='App')),
                ('sent', models.BooleanField(default=False, editable=False, verbose_name='Sent')),
                ('last_attempt', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last attempt')),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailqueue.MailerMessage'),
        ),
    ]
