input {
	beats {
		port => 5000
                # ssl => true
                # ssl_certificate => "/etc/logstash/certs/cert.pem"
                # ssl_key => "/etc/logstash/certs/privkey.pem"
	}
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
                user => "elastic"
                password => "logstashisstretchy"
	}
}

filter {
       if [type] == "imptime" {
           grok {
               match => [ "message" , "%{NOTSPACE:log_level} (?<log_datetimestamp>.{23}) %{POSINT:proc_id} %{NOTSPACE:filename} %{POSINT:line_number}\: %{GREEDYDATA:content}" ]
           }

           json {
               source => "content"
           }

           date {
               match => [ "log_datetimestamp", "ISO8601", "YYYY-MM-dd HH:mm:ss,SSS"]
               target => "@timestamp"
           }
       }
}

