SENTRY_SECRET_KEY="234Cbw34#@23tgasxF%$%^11hjhgda@#$$fFE3fvg33f2FV#3f3@#vvsdd#$#$$tgbbsdae@#$$Tb"
SENTRY_DISABLE_REGISTRATION=True

SENTRY_SERVER_EMAIL=imptime@impd.co.za
SENTRY_EMAIL_HOST=mail.impd.co.za
SENTRY_EMAIL_PASSWORD=<SMTP PASSWORD>
SENTRY_EMAIL_USER=SMTP_Injection
SENTRY_EMAIL_PORT=587
SENTRY_EMAIL_USE_TLS=True

SENTRY_POSTGRES_HOST=XXX
SENTRY_REDIS_HOST=redis

SENTRY_WEB_HOST='0.0.0.0'
