# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timepiece', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=30, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('filename_prefix', models.CharField(max_length=30)),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_comment', models.TextField(blank=True, null=True, verbose_name=b"Comment (doesn't appear on the invoice")),
                ('invoice_number', models.IntegerField(default=0, unique=True)),
                ('client_order_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Optional client order name')),
                ('client_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Optional client order number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('invoice_note', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateField()),
                ('payment_due', models.DateField()),
                ('currency_symbol', models.CharField(choices=[(b'R', b'R'), (b'\xc2\xa3', b'\xc2\xa3'), (b'\xe2\x82\xac', b'\xe2\x82\xac'), (b'bitcoin', b'B')], default=b'R', max_length=3)),
                ('footer_terms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'open', b'Open'), (b'paid', b'Paid'), (b'writtenoff', b'Written Off')], default=b'open', max_length=20)),
                ('vat_rate', models.FloatField(default=0)),
                ('business', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='timepiece.Business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoicing.ClientInvoiceDetails')),
                ('created_by', lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL)),
                ('from_company', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='timepiece.Company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='timepiece.Project')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_units', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid_at', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_comment', models.TextField(blank=True, null=True, verbose_name=b'Comment (not sent to the client)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sent_to_client_at', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'creating', b'Creating'), (b'sent to client', b'Sent to client'), (b'accepted', b'Accepted by client'), (b'rejected', b'Rejected by client'), (b'work done', b'Work done')], default=b'open', max_length=20)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency_symbol', models.CharField(choices=[(b'R', b'R'), (b'\xc2\xa3', b'\xc2\xa3'), (b'\xe2\x82\xac', b'\xe2\x82\xac'), (b'bitcoin', b'B')], default=b'R', max_length=3)),
                ('additional_document', models.FileField(blank=True, max_length=255, null=True, upload_to=lib.fields.UploadTo(b'quotes_additional_documents'))),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='timepiece.Project')),
                ('quote_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timepiece.BusinessDocument')),
            ],
        ),
    ]
