# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='additional_document',
            field=models.FileField(blank=True, null=True, upload_to=lib.fields.UploadTo(b'quotes_additional_documents')),
        ),
    ]
