# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20170826_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoicedetails',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
