# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_clientinvoicedetails_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
