# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models

def forwards(apps, schema_editor):
    Invoice = apps.get_model('invoicing', 'Invoice')
    duplicate_invoice = Invoice.objects.filter(id=589).first()
    if duplicate_invoice is None:
        return
    if duplicate_invoice.invoice_number != 625:
        raise Exception("Sanity fail, Invalid invoice")
    duplicate_invoice.delete()

    duplicate_invoice = Invoice.objects.filter(id=717).first()
    if duplicate_invoice is None:
        return
    if duplicate_invoice.invoice_number != 752:
        raise Exception("Sanity fail, Invalid invoice")
    duplicate_invoice.delete()

    

class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_clientinvoicedetails_archived'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
