# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20171103_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.FloatField(default=0),
        ),
    ]
