# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 10:53
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Invoice = apps.get_model('invoicing', 'Invoice')

    for invoice in Invoice.objects.all():
        if invoice.client.taxable:
            invoice.vat_rate = 0.14
        else:
            invoice.vat_rate = 0
        invoice.save()



class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoice_vat'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
