# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0007_set_existing_vats'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=lib.fields.ProtectedForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
