# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 19:32
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, schema_editor):

    Invoice = apps.get_model('invoicing', 'Invoice')
    Business = apps.get_model('timepiece', 'Business')
    business = Business.objects.get(name='admin')
    Invoice.objects.all().filter(business__isnull=True, project__isnull=True).update(business=business)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_invoice_created_by'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
