# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 19:38
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def migrate(apps, schema_editor):

    Invoice = apps.get_model('invoicing', 'Invoice')
    for x in Invoice.objects.all().filter(business__isnull=True, project__isnull=False):
        x.business_id=x.project.business_id
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_set_all_existing_invoice_projects'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
