# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_set_all_existing_invoice_businesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='timepiece.Business'),
        ),
    ]
