# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 15:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timepiece', '0140_auto_20181027_2153'),
        ('invoicing', '0011_auto_20180326_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='from_company',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='timepiece.Company'),
        ),
    ]
