# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 15:39
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Invoice = apps.get_model('invoicing', 'Invoice')
    Company = apps.get_model('timepiece', 'Company')
    company = Company.objects.get(name="Implicit Design")
    Invoice.objects.all().update(from_company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_invoice_from_company'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
