# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 15:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_update exisitng invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_company',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='timepiece.Company'),
        ),
    ]
